# Generated by Django 5.2.12 on 2026-03-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_moderation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryreply',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional image or video file.', null=True, upload_to='attachments/inquiries/', verbose_name='attachment'),
        ),
    ]
