# Generated by Django 5.2.12 on 2026-03-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visibility_grants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisibilityGrant',
        ),
    ]
