# Generated by Django 5.2.12 on 2026-03-28 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_visibilitygrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('inquiry_new', 'Inquiry new'), ('inquiry_reply', 'Inquiry reply'), ('rfq_new_response', 'RFQ new response'), ('listing_approved', 'Listing approved'), ('rfq_approved', 'RFQ approved'), ('identity_revealed', 'Identity revealed'), ('deal_updated', 'Deal updated'), ('system', 'System')], default='system', max_length=50, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='url')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_actor', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
