# Generated by Django 5.2.12 on 2026-03-28 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_identity_status'),
        ('core', '0004_notification'),
        ('inquiries', '0004_moderation_status'),
        ('rfqs', '0003_alter_rfq_currency_alter_rfq_unit_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('inquiry', 'Inquiry'), ('rfq', 'RFQ')], max_length=20, verbose_name='deal type')),
                ('buyer_accepted', models.BooleanField(default=False)),
                ('seller_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('agreed', 'Agreed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_acceptor', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_trigger', to='inquiries.inquiry')),
                ('rfq_conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_trigger', to='rfqs.rfqconversation')),
                ('seller_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='companies.company')),
                ('seller_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'deal trigger',
                'verbose_name_plural': 'deal triggers',
                'ordering': ['-created_at'],
            },
        ),
    ]
