# Generated by Django 5.2.12 on 2026-03-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_deal_reject_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealtrigger',
            name='buyer_identity_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealtrigger',
            name='seller_identity_revealed',
            field=models.BooleanField(default=False),
        ),
    ]
