from django.db import migrations


LANGUAGE_FIELDS = (
    "text_de",
    "text_ar",
    "text_tr",
    "text_fa",
    "text_fr",
    "text_es",
    "text_pt",
    "text_nl",
    "text_zh",
)


def t(de, ar, tr, fa, fr, es, pt, nl, zh):
    return dict(zip(LANGUAGE_FIELDS, (de, ar, tr, fa, fr, es, pt, nl, zh)))


CMS_TRANSLATIONS = {
    "impressum.address": t(
        "Berlin, Deutschland\nBitte aktualisieren Sie diesen Block vor dem Produktivstart mit Ihrer finalen registrierten Firmenanschrift.",
        "برلين، ألمانيا\nيرجى تحديث هذه الكتلة بعنوان شركتك المسجل النهائي قبل الإطلاق الإنتاجي.",
        "Berlin, Almanya\nLutfen bu blogu canliya cikmadan once nihai sirket adresinizle guncelleyin.",
        "برلین، آلمان\nلطفا پیش از راه اندازی نهایی این بخش را با نشانی ثبت شده نهایی شرکت خود به روز کنید.",
        "Berlin, Allemagne\nVeuillez mettre a jour ce bloc avec l'adresse enregistree finale de votre entreprise avant le lancement en production.",
        "Berlin, Alemania\nActualice este bloque con la direccion registrada final de su empresa antes del lanzamiento en produccion.",
        "Berlim, Alemanha\nAtualize este bloco com a morada registada final da sua empresa antes do lancamento em producao.",
        "Berlijn, Duitsland\nWerk dit blok voor de productielancering bij met het definitieve geregistreerde bedrijfsadres.",
        "德国柏林\n请在正式上线前使用贵公司最终注册地址更新此区块。",
    ),
    "impressum.address_label": t("Registrierte Anschrift", "العنوان المسجل", "Kayitli adres", "نشانی ثبت شده", "Adresse enregistree", "Direccion registrada", "Morada registada", "Geregistreerd adres", "注册地址"),
    "impressum.company_name": t("floos33", "floos33", "floos33", "floos33", "floos33", "floos33", "floos33", "floos33", "floos33"),
    "impressum.company_name_label": t("Firmenname", "اسم الشركة", "Sirket adi", "نام شرکت", "Nom de l'entreprise", "Nombre de la empresa", "Nome da empresa", "Bedrijfsnaam", "公司名称"),
    "impressum.contact_body": t(
        "E-Mail: support@floos33.de\nTelefon: +49 1575 4967414",
        "البريد الإلكتروني: support@floos33.de\nالهاتف: +49 1575 4967414",
        "E-posta: support@floos33.de\nTelefon: +49 1575 4967414",
        "ایمیل: support@floos33.de\nتلفن: +49 1575 4967414",
        "Email : support@floos33.de\nTelephone : +49 1575 4967414",
        "Correo: support@floos33.de\nTelefono: +49 1575 4967414",
        "Email: support@floos33.de\nTelefone: +49 1575 4967414",
        "E-mail: support@floos33.de\nTelefoon: +49 1575 4967414",
        "邮箱：support@floos33.de\n电话：+49 1575 4967414",
    ),
    "impressum.contact_label": t("Kontakt", "الاتصال", "Iletisim", "تماس", "Contact", "Contacto", "Contacto", "Contact", "联系方式"),
    "impressum.eyebrow": t("Impressum", "إمبريسوم", "Impressum", "ایمپرسوم", "Mentions legales", "Aviso legal", "Impressum", "Impressum", "公司信息"),
    "impressum.intro": t(
        "Diese Seite enthält die Betreiberangaben und die Struktur des rechtlichen Hinweises für floos33. Ersetzen Sie diese Startangaben vor dem Launch durch Ihre final registrierten Informationen.",
        "تقدم هذه الصفحة بيانات مشغل المنصة وهيكل الإشعار القانوني الخاص بـ floos33. استبدل هذه البيانات الأولية بمعلوماتك المسجلة النهائية قبل الإطلاق.",
        "Bu sayfa floos33 icin platform operatoru bilgilerini ve yasal bildirim yapisini sunar. Canliya cikmadan once bu baslangic bilgilerini nihai kayitli bilgilerinizle degistirin.",
        "این صفحه جزئیات اپراتور پلتفرم و ساختار اطلاعیه حقوقی floos33 را ارائه می کند. پیش از راه اندازی، این اطلاعات اولیه را با اطلاعات ثبت شده نهایی خود جایگزین کنید.",
        "Cette page fournit les informations sur l'operateur de la plateforme et la structure des mentions legales de floos33. Remplacez ces informations de depart par vos donnees enregistrees finales avant le lancement.",
        "Esta pagina proporciona los datos del operador de la plataforma y la estructura del aviso legal de floos33. Sustituya estos datos iniciales por su informacion registrada final antes del lanzamiento.",
        "Esta pagina fornece os detalhes do operador da plataforma e a estrutura do aviso legal da floos33. Substitua estes dados iniciais pelas suas informacoes registadas finais antes do lancamento.",
        "Deze pagina bevat de exploitantgegevens en de structuur van de juridische kennisgeving voor floos33. Vervang deze startgegevens voor de lancering door uw definitieve geregistreerde informatie.",
        "此页面提供 floos33 平台运营方信息及法律声明结构。请在上线前用贵公司的最终注册信息替换这些初始内容。",
    ),
    "impressum.legal_body": t(
        "Dieser vorläufige rechtliche Hinweis dient dazu, die Seite während der Entwicklung strukturell vollständig zu halten. Ersetzen Sie ihn vor dem Go-live durch rechtssichere Formulierungen und finale Firmendaten für die zuständige Jurisdiktion.",
        "تم توفير هذا الإشعار القانوني الأولي للحفاظ على اكتمال الصفحة من حيث البنية أثناء التطوير. استبدله بصياغة قانونية نهائية وبيانات الشركة النهائية المناسبة للاختصاص القضائي قبل الإطلاق.",
        "Bu baslangic yasal bildirimi, gelistirme sirasinda sayfanin yapisal olarak eksiksiz kalmasi icin saglanmistir. Canliya almadan once bunu ilgili yargi bolgesine uygun nihai hukuki metin ve sirket bilgileriyle degistirin.",
        "این اطلاعیه حقوقی اولیه برای کامل نگه داشتن ساختار صفحه در دوره توسعه ارائه شده است. پیش از انتشار نهایی، آن را با متن حقوقی متناسب با حوزه قضایی و اطلاعات نهایی شرکت جایگزین کنید.",
        "Cette mention legale provisoire est fournie pour conserver une page structurellement complete pendant le developpement. Remplacez-la avant la mise en ligne par un texte juridique adapte a la juridiction concernee et par les informations finales de l'entreprise.",
        "Este aviso legal inicial se incluye para mantener la pagina estructuralmente completa durante el desarrollo. Sustituyalo antes de publicar por el texto juridico final segun la jurisdiccion y los datos definitivos de la empresa.",
        "Este aviso legal inicial e fornecido para manter a pagina estruturalmente completa durante o desenvolvimento. Substitua-o antes de entrar em producao por texto juridico final adequado a jurisdicao e pelos dados finais da empresa.",
        "Deze voorlopige juridische kennisgeving houdt de pagina tijdens de ontwikkeling structureel volledig. Vervang deze voor livegang door definitieve juridische tekst voor de juiste jurisdictie en de definitieve bedrijfsgegevens.",
        "此临时法律声明用于在开发期间保持页面结构完整。请在正式上线前将其替换为适用于相应司法管辖区的最终法律文本和公司信息。",
    ),
    "impressum.legal_title": t("Rechtlicher Hinweis", "إشعار قانوني", "Yasal bildirim", "اطلاعیه حقوقی", "Mentions legales", "Aviso legal", "Aviso legal", "Juridische kennisgeving", "法律声明"),
    "impressum.meta_description": t("Betreiberangaben und rechtlicher Hinweis für floos33.", "بيانات مشغل المنصة والإشعار القانوني لـ floos33.", "floos33 icin platform operatoru bilgileri ve yasal bildirim.", "اطلاعات اپراتور پلتفرم و اطلاعیه حقوقی floos33.", "Informations sur l'operateur et mentions legales de floos33.", "Datos del operador y aviso legal de floos33.", "Detalhes do operador da plataforma e aviso legal da floos33.", "Platformexploitant en juridische kennisgeving voor floos33.", "floos33 的平台运营方信息和法律声明。"),
    "impressum.meta_title": t("Impressum", "إمبريسوم", "Impressum", "ایمپرسوم", "Mentions legales", "Aviso legal", "Impressum", "Impressum", "公司信息"),
    "impressum.registration": t(
        "Bitte aktualisieren Sie diesen Block mit dem Handelsregistergericht und der Registernummer, falls zutreffend.",
        "يرجى تحديث هذه الكتلة باسم المحكمة التجارية ورقم السجل إذا كان ذلك ينطبق.",
        "Uygunsa, lutfen bu blogu ticaret sicili mahkemesi ve numarasi ile guncelleyin.",
        "در صورت لزوم، لطفا این بخش را با دادگاه ثبت تجاری و شماره ثبت به روز کنید.",
        "Veuillez mettre a jour ce bloc avec le tribunal du registre du commerce et le numero d'enregistrement, le cas echeant.",
        "Actualice este bloque con el juzgado del registro mercantil y el numero de registro, si procede.",
        "Atualize este bloco com o tribunal do registo comercial e o numero de registo, se aplicavel.",
        "Werk dit blok indien van toepassing bij met de handelsregisterrechtbank en het registratienummer.",
        "如适用，请使用商业登记法院和登记号更新此区块。",
    ),
    "impressum.registration_label": t("Handelsregister", "السجل التجاري", "Ticaret sicili", "ثبت تجاری", "Registre du commerce", "Registro mercantil", "Registo comercial", "Handelsregister", "商业登记"),
    "impressum.representative": t(
        "Bitte aktualisieren Sie diesen Block mit der verantwortlichen gesetzlichen Vertretung.",
        "يرجى تحديث هذه الكتلة باسم الممثل القانوني المسؤول.",
        "Lutfen bu blogu sorumlu yasal temsilci bilgisiyle guncelleyin.",
        "لطفا این بخش را با نماینده قانونی مسئول به روز کنید.",
        "Veuillez mettre a jour ce bloc avec le representant legal responsable.",
        "Actualice este bloque con el representante legal responsable.",
        "Atualize este bloco com o representante legal responsavel.",
        "Werk dit blok bij met de verantwoordelijke wettelijke vertegenwoordiger.",
        "请使用负责的法定代表人信息更新此区块。",
    ),
    "impressum.representative_label": t("Vertretungsberechtigte Person", "الممثل القانوني", "Yetkili temsilci", "نماینده مجاز", "Representant autorise", "Representante autorizado", "Representante autorizado", "Bevoegde vertegenwoordiger", "授权代表"),
    "impressum.title": t("Impressum / Anbieterkennzeichnung", "إمبريسوم / البيانات القانونية", "Impressum / Kunyeler", "ایمپرسوم / مشخصات قانونی", "Mentions legales / Imprint", "Impressum / Aviso legal", "Impressum / Identificacao legal", "Impressum / Juridische gegevens", "公司信息 / 法律标识"),
    "impressum.vat": t(
        "Bitte aktualisieren Sie diesen Block mit der Umsatzsteuer-Identifikationsnummer, falls zutreffend.",
        "يرجى تحديث هذه الكتلة برقم ضريبة القيمة المضافة إذا كان ذلك ينطبق.",
        "Uygunsa, lutfen bu blogu KDV kimlik numarasi ile guncelleyin.",
        "در صورت لزوم، لطفا این بخش را با شماره شناسایی مالیات بر ارزش افزوده به روز کنید.",
        "Veuillez mettre a jour ce bloc avec le numero de TVA intracommunautaire, le cas echeant.",
        "Actualice este bloque con el numero de IVA, si corresponde.",
        "Atualize este bloco com o numero de identificacao de IVA, se aplicavel.",
        "Werk dit blok indien van toepassing bij met het btw-identificatienummer.",
        "如适用，请使用增值税识别号更新此区块。",
    ),
    "impressum.vat_label": t("USt-IdNr.", "رقم ضريبة القيمة المضافة", "KDV No", "شناسه مالیات بر ارزش افزوده", "Numero de TVA", "IVA", "NIF IVA", "Btw-nummer", "增值税号"),
    "privacy.eyebrow": t("Datenschutz", "الخصوصية", "Gizlilik", "حریم خصوصی", "Confidentialite", "Privacidad", "Privacidade", "Privacy", "隐私"),
    "privacy.intro": t(
        "Diese Seite erläutert, wie plattformeigene Daten und Kontoaktivitäten auf floos33 verarbeitet werden. Aktualisieren Sie die endgültige rechtliche Formulierung vor dem Produktivstart.",
        "توضح هذه الصفحة كيفية التعامل مع بيانات المنصة ونشاط الحساب على floos33. حدّث الصياغة القانونية النهائية قبل الإطلاق الإنتاجي.",
        "Bu sayfa, floos33 uzerindeki platform verilerinin ve hesap etkinliklerinin nasil islendiyini aciklar. Canliya cikmadan once nihai hukuki metni guncelleyin.",
        "این صفحه توضیح می دهد که داده های متعلق به پلتفرم و فعالیت حساب در floos33 چگونه مدیریت می شوند. پیش از راه اندازی، متن حقوقی نهایی را به روز کنید.",
        "Cette page explique comment les donnees de la plateforme et l'activite des comptes sont traitees sur floos33. Mettez a jour la formulation juridique finale avant le lancement en production.",
        "Esta pagina explica como se gestionan los datos de la plataforma y la actividad de la cuenta en floos33. Actualice la redaccion legal final antes del lanzamiento en produccion.",
        "Esta pagina explica como os dados da plataforma e a atividade da conta sao tratados na floos33. Atualize a redacao juridica final antes do lancamento em producao.",
        "Deze pagina legt uit hoe platformdata en accountactiviteit op floos33 worden behandeld. Werk de definitieve juridische formulering bij voor de productielancering.",
        "此页面说明 floos33 如何处理平台数据和账户活动。请在正式上线前更新最终法律文本。",
    ),
    "privacy.meta_description": t(
        "Lesen Sie, wie floos33 Kontoinformationen, Plattformdaten, Kommunikationsprotokolle und Supportanfragen verarbeitet.",
        "اقرأ كيف تتعامل floos33 مع معلومات الحساب وبيانات المنصة وسجلات الاتصال وطلبات الدعم.",
        "floos33'in hesap bilgilerini, platform verilerini, iletisim kayitlarini ve destek taleplerini nasil isledigini okuyun.",
        "بخوانید که floos33 چگونه اطلاعات حساب، داده های پلتفرم، سوابق ارتباطی و درخواست های پشتیبانی را مدیریت می کند.",
        "Decouvrez comment floos33 traite les informations de compte, les donnees de plateforme, les enregistrements de communication et les demandes de support.",
        "Lea como floos33 gestiona la informacion de la cuenta, los datos de la plataforma, los registros de comunicacion y las solicitudes de soporte.",
        "Leia como a floos33 trata a informacao da conta, os dados da plataforma, os registos de comunicacao e os pedidos de suporte.",
        "Lees hoe floos33 accountinformatie, platformdata, communicatiegegevens en supportverzoeken verwerkt.",
        "了解 floos33 如何处理账户信息、平台数据、通信记录和支持请求。",
    ),
    "privacy.meta_title": t("Datenschutzerklärung", "سياسة الخصوصية", "Gizlilik Politikasi", "سیاست حریم خصوصی", "Politique de confidentialite", "Politica de privacidad", "Politica de privacidade", "Privacybeleid", "隐私政策"),
    "privacy.section_1_body": t(
        "Wir erfassen Kontodaten, Unternehmensdaten, Marktplatz-Einreichungen, RFQs, Kontaktanfragen und Plattformaktivitäten, die für den Betrieb des Dienstes erforderlich sind.",
        "نجمع بيانات الحساب وبيانات الشركة ومواد السوق المرسلة وطلبات الشراء ورسائل الاتصال ونشاط المنصة اللازم لتشغيل الخدمة.",
        "Hizmeti isletmek icin gerekli hesap bilgilerini, sirket bilgilerini, pazaryeri gonderimlerini, RFQ'lari, iletisim mesajlarini ve platform etkinliklerini toplariz.",
        "ما جزئیات حساب، اطلاعات شرکت، ارسال های بازار، RFQها، پیام های تماس و فعالیت های پلتفرم موردنیاز برای ارائه خدمت را جمع آوری می کنیم.",
        "Nous collectons les details de compte, les details d'entreprise, les soumissions marketplace, les RFQ, les messages de contact et l'activite de plateforme necessaires au fonctionnement du service.",
        "Recopilamos datos de cuenta, datos de empresa, envios del marketplace, RFQ, mensajes de contacto y actividad de la plataforma necesarios para operar el servicio.",
        "Recolhemos dados de conta, dados da empresa, submissões do marketplace, RFQs, mensagens de contacto e atividade da plataforma necessarios para operar o servico.",
        "We verzamelen accountgegevens, bedrijfsgegevens, marketplace-inzendingen, RFQ's, contactberichten en platformactiviteit die nodig zijn om de dienst te exploiteren.",
        "我们收集运营服务所需的账户信息、公司信息、市场提交内容、RFQ、联系消息和平台活动数据。",
    ),
    "privacy.section_1_title": t("Welche Daten wir erfassen", "البيانات التي نجمعها", "Topladigimiz veriler", "داده هایی که جمع آوری می کنیم", "Donnees que nous collectons", "Datos que recopilamos", "Dados que recolhemos", "Welke gegevens we verzamelen", "我们收集的数据"),
    "privacy.section_2_body": t(
        "Die Daten werden verwendet, um den Marktplatz zu betreiben, Konten zu verifizieren, Listings und RFQs zu moderieren, Supportanfragen zu beantworten und den Plattformbetrieb zu verbessern.",
        "تُستخدم البيانات لتشغيل السوق والتحقق من الحسابات ومراجعة العروض وطلبات الشراء والرد على طلبات الدعم وتحسين تشغيل المنصة.",
        "Veriler, pazaryerini calistirmak, hesaplari dogrulamak, ilanlari ve RFQ'lari denetlemek, destek taleplerini yanitlamak ve platform operasyonlarini iyilestirmek icin kullanilir.",
        "داده ها برای اداره بازار، تایید حساب ها، مدیریت فهرست ها و RFQها، پاسخ به درخواست های پشتیبانی و بهبود عملیات پلتفرم استفاده می شوند.",
        "Les donnees servent a exploiter la marketplace, verifier les comptes, moderer les annonces et les RFQ, repondre aux demandes d'assistance et ameliorer les operations de la plateforme.",
        "Los datos se utilizan para operar el marketplace, verificar cuentas, moderar listados y RFQ, responder solicitudes de soporte y mejorar las operaciones de la plataforma.",
        "Os dados sao usados para operar o marketplace, verificar contas, moderar listagens e RFQs, responder a pedidos de suporte e melhorar as operacoes da plataforma.",
        "Gegevens worden gebruikt om de marketplace te beheren, accounts te verifieren, vermeldingen en RFQ's te modereren, supportverzoeken te beantwoorden en platformprocessen te verbeteren.",
        "这些数据用于运行市场平台、验证账户、审核列表和 RFQ、回应支持请求以及改进平台运营。",
    ),
    "privacy.section_2_title": t("Warum wir sie nutzen", "لماذا نستخدمها", "Neden kullaniyoruz", "چرا از آنها استفاده می کنیم", "Pourquoi nous les utilisons", "Por que los usamos", "Porque os usamos", "Waarom we ze gebruiken", "我们为何使用这些数据"),
    "privacy.section_3_body": t(
        "Autorisierte Plattformadministratoren können auf Daten zugreifen, die für Moderation, Support, Compliance und Sicherheitsprüfungen erforderlich sind. Öffentliche Besucher sehen nur genehmigte öffentliche Inhalte.",
        "يمكن لمسؤولي المنصة المصرح لهم الوصول إلى البيانات اللازمة للمراجعة والدعم والامتثال والأمن. ولا يرى الزوار العامون إلا المحتوى العام المعتمد.",
        "Yetkili platform yoneticileri moderasyon, destek, uyumluluk ve guvenlik incelemeleri icin gerekli verilere erisebilir. Genel ziyaretciler yalnizca onayli herkese acik icerigi gorur.",
        "مدیران مجاز پلتفرم می توانند به داده های لازم برای نظارت، پشتیبانی، انطباق و بررسی های امنیتی دسترسی داشته باشند. بازدیدکنندگان عمومی فقط محتوای عمومی تاییدشده را می بینند.",
        "Les administrateurs autorises de la plateforme peuvent acceder aux donnees necessaires a la moderation, au support, a la conformite et aux revues de securite. Les visiteurs publics ne voient que le contenu public approuve.",
        "Los administradores autorizados de la plataforma pueden acceder a los datos necesarios para moderacion, soporte, cumplimiento y revisiones de seguridad. Los visitantes publicos solo ven contenido publico aprobado.",
        "Os administradores autorizados da plataforma podem aceder aos dados necessarios para moderacao, suporte, conformidade e revisoes de seguranca. Os visitantes publicos apenas veem conteudo publico aprovado.",
        "Geautoriseerde platformbeheerders hebben toegang tot gegevens die nodig zijn voor moderatie, ondersteuning, compliance en veiligheidscontroles. Openbare bezoekers zien alleen goedgekeurde publieke content.",
        "获授权的平台管理员可以访问审核、支持、合规和安全审查所需的数据。公开访客只能看到已批准的公开内容。",
    ),
    "privacy.section_3_title": t("Wer darauf zugreifen kann", "من يمكنه الوصول إليها", "Kimler erisebilir", "چه کسانی می توانند دسترسی داشته باشند", "Qui peut y acceder", "Quien puede acceder", "Quem pode aceder", "Wie toegang heeft", "谁可以访问"),
    "privacy.section_4_body": t(
        "Wir speichern Plattformdaten so lange, wie es für den Betrieb des Dienstes, gesetzliche Pflichten oder die Bearbeitung von Streitfällen erforderlich ist. Kontaktieren Sie den Plattformbetreiber für Konto- oder Datenanfragen.",
        "نحتفظ ببيانات المنصة طالما كان ذلك ضرورياً لتشغيل الخدمة أو الالتزامات القانونية أو معالجة النزاعات. تواصل مع مشغل المنصة لطلبات الحساب أو البيانات.",
        "Platform verilerini hizmetin isletimi, yasal yukumlulukler veya uyusmazlik yonetimi icin gerekli oldugu sure boyunca saklariz. Hesap veya veri talepleri icin platform operatoruyle iletisime gecin.",
        "ما داده های پلتفرم را تا زمانی که برای بهره برداری از سرویس، تعهدات قانونی یا رسیدگی به اختلافات لازم باشد نگه می داریم. برای درخواست های مربوط به حساب یا داده با اپراتور پلتفرم تماس بگیرید.",
        "Nous conservons les donnees de la plateforme aussi longtemps que necessaire pour le fonctionnement du service, les obligations legales ou la gestion des litiges. Contactez l'operateur de la plateforme pour toute demande liee au compte ou aux donnees.",
        "Conservamos los datos de la plataforma durante el tiempo necesario para operar el servicio, cumplir obligaciones legales o gestionar disputas. Contacte con el operador de la plataforma para solicitudes de cuenta o datos.",
        "Conservamos os dados da plataforma durante o tempo necessario para a operacao do servico, obrigacoes legais ou gestao de disputas. Contacte o operador da plataforma para pedidos sobre conta ou dados.",
        "We bewaren platformgegevens zolang dat nodig is voor de dienst, wettelijke verplichtingen of geschilafhandeling. Neem contact op met de platformexploitant voor account- of gegevensverzoeken.",
        "我们会在服务运营、法律义务或争议处理所需的期限内保留平台数据。如需账户或数据请求，请联系平台运营方。",
    ),
    "privacy.section_4_title": t("Speicherung und Kontrolle", "الاحتفاظ والتحكم", "Saklama ve kontrol", "نگهداری و کنترل", "Conservation et controle", "Retencion y control", "Retencao e controlo", "Bewaring en controle", "保留与控制"),
    "privacy.title": t("Datenschutzerklärung", "سياسة الخصوصية", "Gizlilik Politikasi", "سیاست حریم خصوصی", "Politique de confidentialite", "Politica de privacidad", "Politica de privacidade", "Privacybeleid", "隐私政策"),
    "terms.eyebrow": t("AGB", "الشروط", "Kosullar", "شرایط", "Conditions", "Terminos", "Termos", "Voorwaarden", "条款"),
    "terms.intro": t(
        "Diese vorläufigen Bedingungen beschreiben die grundlegenden Plattformregeln für den Zugriff auf floos33. Ersetzen Sie sie vor dem Launch durch die endgültige rechtliche Fassung.",
        "تصف هذه الشروط الأولية القواعد الأساسية للوصول إلى منصة floos33. استبدلها بالصياغة القانونية النهائية قبل الإطلاق.",
        "Bu baslangic kosullari, floos33'e erisim icin temel platform kurallarini aciklar. Canliya cikmadan once bunlari nihai hukuki metinle degistirin.",
        "این شرایط اولیه، قواعد اصلی پلتفرم برای دسترسی به floos33 را توضیح می دهد. پیش از راه اندازی، آنها را با متن حقوقی نهایی جایگزین کنید.",
        "Ces conditions initiales decrivent les regles de base de la plateforme pour acceder a floos33. Remplacez-les par la version juridique definitive avant le lancement.",
        "Estos terminos iniciales describen las reglas basicas de la plataforma para acceder a floos33. Sustituyalos por la redaccion legal final antes del lanzamiento.",
        "Estes termos iniciais descrevem as regras basicas da plataforma para aceder a floos33. Substitua-os pela redacao juridica final antes do lancamento.",
        "Deze startvoorwaarden beschrijven de basisregels van het platform voor toegang tot floos33. Vervang ze voor de lancering door de definitieve juridische tekst.",
        "这些初始条款说明了访问 floos33 的基本平台规则。请在上线前替换为最终法律文本。",
    ),
    "terms.meta_description": t(
        "Prüfen Sie die wichtigsten Plattformbedingungen für die Nutzung von floos33, einschließlich Marktplatzregeln, Moderation und Kontoverantwortung.",
        "راجع الشروط الرئيسية لاستخدام floos33، بما في ذلك قواعد السوق والإشراف ومسؤوليات الحساب.",
        "Pazaryeri kurallari, moderasyon ve hesap sorumluluklari dahil floos33'i kullanmaya iliskin temel platform kosullarini inceleyin.",
        "شرایط اصلی پلتفرم برای استفاده از floos33 شامل قواعد بازار، نظارت و مسئولیت های حساب را بررسی کنید.",
        "Consultez les principales conditions de la plateforme pour utiliser floos33, y compris les regles marketplace, la moderation et les responsabilites de compte.",
        "Revise las condiciones principales de la plataforma para usar floos33, incluidas las reglas del marketplace, la moderacion y las responsabilidades de la cuenta.",
        "Reveja os principais termos da plataforma para usar a floos33, incluindo regras do marketplace, moderacao e responsabilidades da conta.",
        "Bekijk de belangrijkste platformvoorwaarden voor het gebruik van floos33, inclusief marketplace-regels, moderatie en accountverantwoordelijkheden.",
        "查看使用 floos33 的主要平台条款，包括市场规则、审核以及账户责任。",
    ),
    "terms.meta_title": t("Nutzungsbedingungen", "شروط الخدمة", "Hizmet Sartlari", "شرایط خدمات", "Conditions d'utilisation", "Terminos del servicio", "Termos de servico", "Servicevoorwaarden", "服务条款"),
    "terms.section_1_body": t(
        "Nutzer müssen korrekte Kontoinformationen angeben und ihre Zugangsdaten sicher verwahren. Der Plattformzugang kann bei Missbrauch oder Richtlinienverstößen eingeschränkt oder entzogen werden.",
        "يجب على المستخدمين تقديم معلومات حساب دقيقة والحفاظ على بيانات الدخول آمنة. قد يتم تقييد الوصول إلى المنصة أو سحبه في حال سوء الاستخدام أو مخالفة السياسات.",
        "Kullanicilar dogru hesap bilgileri vermeli ve giris bilgilerini guvende tutmalidir. Kotuye kullanim veya politika ihlali durumunda platform erisimi kisitlanabilir ya da kaldirilabilir.",
        "کاربران باید اطلاعات دقیق حساب ارائه دهند و مشخصات ورود خود را ایمن نگه دارند. دسترسی به پلتفرم در صورت سوءاستفاده یا نقض سیاست ها می تواند محدود یا لغو شود.",
        "Les utilisateurs doivent fournir des informations de compte exactes et conserver leurs identifiants en securite. L'acces a la plateforme peut etre limite ou revoque en cas d'abus ou de violation des politiques.",
        "Los usuarios deben proporcionar informacion de cuenta precisa y mantener seguras sus credenciales. El acceso a la plataforma puede limitarse o revocarse por uso indebido o incumplimiento de las politicas.",
        "Os utilizadores devem fornecer informacoes de conta corretas e manter as credenciais seguras. O acesso a plataforma pode ser limitado ou revogado por uso indevido ou violacao das politicas.",
        "Gebruikers moeten correcte accountinformatie verstrekken en hun inloggegevens veilig bewaren. Platformtoegang kan worden beperkt of ingetrokken bij misbruik of schending van beleid.",
        "用户必须提供准确的账户信息并妥善保管登录凭证。如发生滥用或违反政策，平台访问权限可能被限制或撤销。",
    ),
    "terms.section_1_title": t("Plattformzugang", "الوصول إلى المنصة", "Platform erisimi", "دسترسی به پلتفرم", "Acces a la plateforme", "Acceso a la plataforma", "Acesso a plataforma", "Platformtoegang", "平台访问"),
    "terms.section_2_body": t(
        "Verkäufer und Käufer bleiben für die von ihnen eingereichten Inhalte verantwortlich. floos33 kann Einreichungen prüfen, genehmigen, ablehnen oder entfernen, um Qualität und Sicherheit des Marktplatzes zu wahren.",
        "يبقى البائعون والمشترون مسؤولين عن المحتوى الذي يقدمونه. ويمكن لـ floos33 مراجعة المشاركات أو الموافقة عليها أو رفضها أو إزالتها للحفاظ على جودة السوق وسلامته.",
        "Saticilar ve alicilar gonderdikleri icerikten sorumlu olmaya devam eder. floos33, pazaryeri kalitesi ve guvenligini korumak icin gonderimleri inceleyebilir, onaylayabilir, reddedebilir veya kaldirabilir.",
        "فروشندگان و خریداران همچنان مسئول محتوایی هستند که ارسال می کنند. floos33 می تواند برای حفظ کیفیت و ایمنی بازار، محتواها را بررسی، تایید، رد یا حذف کند.",
        "Les vendeurs et les acheteurs restent responsables du contenu qu'ils soumettent. floos33 peut examiner, approuver, rejeter ou supprimer des soumissions afin de maintenir la qualite et la securite de la marketplace.",
        "Los vendedores y compradores siguen siendo responsables del contenido que envian. floos33 puede revisar, aprobar, rechazar o eliminar envios para mantener la calidad y seguridad del marketplace.",
        "Os vendedores e compradores continuam responsaveis pelo conteudo que submetem. A floos33 pode rever, aprovar, rejeitar ou remover submissões para manter a qualidade e a seguranca do marketplace.",
        "Verkopers en kopers blijven verantwoordelijk voor de inhoud die zij indienen. floos33 kan inzendingen beoordelen, goedkeuren, afwijzen of verwijderen om de kwaliteit en veiligheid van de marketplace te behouden.",
        "卖家和买家仍需对其提交的内容负责。floos33 可审核、批准、拒绝或移除提交内容，以维护市场质量与安全。",
    ),
    "terms.section_2_title": t("Listings und RFQs", "العروض وطلبات الشراء", "Ilanlar ve RFQ'lar", "فهرست ها و RFQها", "Annonces et RFQ", "Listados y RFQ", "Listagens e RFQs", "Vermeldingen en RFQ's", "列表与 RFQ"),
    "terms.section_3_body": t(
        "Plattformgespräche, Offenlegungsanfragen und Deal-Meilensteine können moderiert werden. Nutzer müssen Betrug, Missbrauch, Spam, unrechtmäßige Handelsaktivitäten und irreführende Informationen vermeiden.",
        "قد تتم مراجعة محادثات المنصة وطلبات كشف الهوية ومراحل الصفقة. ويجب على المستخدمين تجنب الاحتيال والإساءة والبريد المزعج والنشاط التجاري غير القانوني والمعلومات المضللة.",
        "Platform konusmalari, kimlik acma talepleri ve anlasma asamalari denetlenebilir. Kullanicilar dolandiricilikten, kotuye kullanimdan, spamden, yasa disi ticaretten ve yaniltici bilgilerden kacinmalidir.",
        "گفتگوهای پلتفرم، درخواست های افشای هویت و نقاط عطف معامله ممکن است نظارت شوند. کاربران باید از تقلب، سوءاستفاده، اسپم، فعالیت تجاری غیرقانونی و اطلاعات گمراه کننده خودداری کنند.",
        "Les conversations de la plateforme, les demandes de revelation et les etapes de transaction peuvent etre moderees. Les utilisateurs doivent eviter la fraude, les abus, le spam, les activites commerciales illegales et les informations trompeuses.",
        "Las conversaciones de la plataforma, las solicitudes de revelacion y los hitos de la operacion pueden ser moderados. Los usuarios deben evitar fraude, abuso, spam, actividad comercial ilegal e informacion enganosa.",
        "As conversas na plataforma, os pedidos de revelacao e os marcos das negociacoes podem ser moderados. Os utilizadores devem evitar fraude, abuso, spam, atividade comercial ilegal e informacoes enganosas.",
        "Platformgesprekken, onthullingsverzoeken en dealmijlpalen kunnen worden gemodereerd. Gebruikers moeten fraude, misbruik, spam, onwettige handelsactiviteiten en misleidende informatie vermijden.",
        "平台对话、身份揭示请求和交易里程碑可能会被审核。用户必须避免欺诈、滥用、垃圾信息、非法贸易活动和误导性信息。",
    ),
    "terms.section_3_title": t("Moderation und Kommunikation", "الإشراف والتواصل", "Moderasyon ve iletisim", "نظارت و ارتباط", "Moderation et communication", "Moderacion y comunicacion", "Moderacao e comunicacao", "Moderatie en communicatie", "审核与沟通"),
    "terms.section_4_body": t(
        "Die Plattform kann sich im Laufe der Zeit weiterentwickeln. Bedingungen, Workflows und Funktionszugänge können aktualisiert werden, um Compliance, Sicherheit und operative Stabilität zu verbessern.",
        "قد تتطور المنصة بمرور الوقت. ويمكن تحديث الشروط وسير العمل والوصول إلى الميزات عند الحاجة لتحسين الامتثال والأمان والاستقرار التشغيلي.",
        "Platform zamanla gelisebilir. Uyumlulugu, guvenligi ve operasyonel istikrari artirmak icin kosullar, akislar ve ozellik erisimi gerektiginde guncellenebilir.",
        "پلتفرم ممکن است با گذر زمان تکامل یابد. شرایط، فرایندها و دسترسی به قابلیت ها در صورت نیاز برای بهبود انطباق، امنیت و پایداری عملیاتی به روز می شوند.",
        "La plateforme peut evoluer avec le temps. Les conditions, workflows et acces aux fonctionnalites peuvent etre mis a jour pour ameliorer la conformite, la securite et la stabilite operationnelle.",
        "La plataforma puede evolucionar con el tiempo. Los terminos, flujos de trabajo y acceso a funciones pueden actualizarse para mejorar el cumplimiento, la seguridad y la estabilidad operativa.",
        "A plataforma pode evoluir ao longo do tempo. Os termos, fluxos de trabalho e acessos a funcionalidades podem ser atualizados quando necessario para melhorar a conformidade, a seguranca e a estabilidade operacional.",
        "Het platform kan in de loop van de tijd evolueren. Voorwaarden, workflows en toegang tot functies kunnen worden bijgewerkt om compliance, veiligheid en operationele stabiliteit te verbeteren.",
        "平台可能会随着时间发展而演变。条款、工作流程和功能访问权限可在需要时更新，以提升合规性、安全性和运营稳定性。",
    ),
    "terms.section_4_title": t("Haftung und Aktualisierungen", "المسؤولية والتحديثات", "Sorumluluk ve guncellemeler", "مسئولیت و به روزرسانی ها", "Responsabilite et mises a jour", "Responsabilidad y actualizaciones", "Responsabilidade e atualizacoes", "Aansprakelijkheid en updates", "责任与更新"),
    "terms.title": t("Nutzungsbedingungen", "شروط الخدمة", "Hizmet Sartlari", "شرایط خدمات", "Conditions d'utilisation", "Terminos del servicio", "Termos de servico", "Servicevoorwaarden", "服务条款"),
}


def fill_cms_translations(apps, schema_editor):
    CMSBlock = apps.get_model("core", "CMSBlock")

    for block in CMSBlock.objects.filter(key__in=CMS_TRANSLATIONS):
        values = CMS_TRANSLATIONS[block.key]
        for field_name, value in values.items():
            setattr(block, field_name, value)
        block.save(update_fields=[*LANGUAGE_FIELDS, "updated_at"])


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_fill_cms_all_languages"),
    ]

    operations = [
        migrations.RunPython(fill_cms_translations, noop),
    ]
