from django.db import migrations


LANGUAGE_FIELDS = (
    "text_de",
    "text_ar",
    "text_tr",
    "text_fa",
    "text_fr",
    "text_es",
    "text_pt",
    "text_nl",
    "text_zh",
)


def t(de, ar, tr, fa, fr, es, pt, nl, zh):
    return dict(zip(LANGUAGE_FIELDS, (de, ar, tr, fa, fr, es, pt, nl, zh)))


CMS_TRANSLATIONS = {
    "home.cta_section_description": t(
        "Durchsuchen Sie den Marktplatz oder erstellen Sie Ihr Konto, um mit Verifizierung und Aufsicht zu handeln.",
        "تصفح السوق أو أنشئ حسابك للتجارة مع التحقق والإشراف.",
        "Pazaryerine goz atin veya dogrulama ve gozetimle ticaret yapmak icin hesabinizi olusturun.",
        "بازار را مرور کنید یا حساب خود را بسازید تا با تایید و نظارت معامله کنید.",
        "Parcourez la marketplace ou creez votre compte pour commercer avec verification et supervision.",
        "Explore el marketplace o cree su cuenta para comerciar con verificacion y supervision.",
        "Explore o marketplace ou crie a sua conta para negociar com verificacao e supervisao.",
        "Bekijk de marketplace of maak uw account aan om met verificatie en toezicht te handelen.",
        "浏览市场或创建账户，在验证和监管下开展交易。",
    ),
    "home.cta_section_primary": t("Jetzt loslegen", "ابدأ التصفح", "Goz atmaya basla", "شروع مرور", "Commencer a parcourir", "Empezar a explorar", "Comecar a navegar", "Begin met bekijken", "开始浏览"),
    "home.cta_section_secondary": t("Konto erstellen", "إنشاء حساب", "Hesap olustur", "ایجاد حساب", "Creer un compte", "Crear cuenta", "Criar conta", "Account aanmaken", "创建账户"),
    "home.cta_section_title": t("Bereit für den Start?", "جاهز للبدء؟", "Baslamaya hazir misiniz?", "برای شروع آماده اید؟", "Pret a commencer ?", "Listo para empezar?", "Pronto para comecar?", "Klaar om te beginnen?", "准备开始了吗？"),
    "home.hero_badge_admin_approved": t("Admin-geprüfte Listings", "عروض معتمدة من الإدارة", "Yonetici onayli ilanlar", "فهرست های تاییدشده توسط ادمین", "Annonces approuvees par l'admin", "Listados aprobados por admin", "Listagens aprovadas pelo admin", "Door admin goedgekeurde vermeldingen", "管理员已批准的列表"),
    "home.hero_badge_controlled_deal_flow": t("Kontrollierter Deal-Flow", "تدفق صفقات مضبوط", "Kontrollu anlasma akisi", "جریان کنترل شده معامله", "Flux de transaction controle", "Flujo de operaciones controlado", "Fluxo de negociacao controlado", "Gecontroleerde dealflow", "受控交易流程"),
    "home.hero_badge_identity_protection": t("Identitätsschutz", "حماية الهوية", "Kimlik korumasi", "حفاظت از هویت", "Protection de l'identite", "Proteccion de identidad", "Protecao de identidade", "Identiteitsbescherming", "身份保护"),
    "home.hero_badge_verified_users": t("Verifizierte Nutzer", "مستخدمون موثّقون", "Dogrulanmis kullanicilar", "کاربران تاییدشده", "Utilisateurs verifies", "Usuarios verificados", "Utilizadores verificados", "Geverifieerde gebruikers", "已验证用户"),
    "home.hero_cta_primary": t("Marktplatz durchsuchen", "تصفح السوق", "Pazaryerini gez", "مرور بازار", "Parcourir la marketplace", "Explorar marketplace", "Explorar marketplace", "Marketplace bekijken", "浏览市场"),
    "home.hero_cta_primary_guest": t("Konto erstellen", "إنشاء حساب", "Hesap olustur", "ایجاد حساب", "Creer un compte", "Crear cuenta", "Criar conta", "Account aanmaken", "创建账户"),
    "home.hero_cta_secondary": t("RFQs durchsuchen", "تصفح طلبات الشراء", "RFQ'lara goz at", "مرور RFQها", "Parcourir les RFQ", "Explorar RFQ", "Explorar RFQs", "RFQ's bekijken", "浏览 RFQ"),
    "home.hero_cta_secondary_guest": t("Marktplatz durchsuchen", "تصفح السوق", "Pazaryerini gez", "مرور بازار", "Parcourir la marketplace", "Explorar marketplace", "Explorar marketplace", "Marketplace bekijken", "浏览市场"),
    "home.hero_description": t(
        "Durchsuchen Sie genehmigte Listings, veröffentlichen Sie RFQs, verhandeln Sie vertraulich und bringen Sie jeden Deal unter Plattformaufsicht mit Identitätsschutz und Verifizierung voran.",
        "تصفح العروض المعتمدة، وانشر طلبات الشراء، وتفاوض بشكل خاص، وادفع كل صفقة إلى الأمام تحت إشراف المنصة مع حماية الهوية والتحقق.",
        "Onayli ilanlari inceleyin, RFQ yayinlayin, ozel olarak pazarlik yapin ve her anlasmayi kimlik korumasi ve dogrulama ile platform gozetimi altinda ilerletin.",
        "فهرست های تاییدشده را مرور کنید، RFQ ثبت کنید، به صورت خصوصی مذاکره کنید و هر معامله را با حفاظت هویت و تایید تحت نظارت پلتفرم پیش ببرید.",
        "Parcourez les annonces approuvees, publiez des RFQ, negociez en prive et faites progresser chaque transaction sous la supervision de la plateforme avec protection d'identite et verification.",
        "Explore listados aprobados, publique RFQ, negocie en privado y haga avanzar cada operacion bajo supervision de la plataforma con proteccion de identidad y verificacion.",
        "Explore listagens aprovadas, publique RFQs, negoceie em privado e faca avancar cada negocio sob supervisao da plataforma com protecao de identidade e verificacao.",
        "Bekijk goedgekeurde vermeldingen, plaats RFQ's, onderhandel privé en laat elke deal onder platformtoezicht vooruitgaan met identiteitsbescherming en verificatie.",
        "浏览已批准的列表、发布 RFQ、私密协商，并在身份保护和验证支持下在平台监管中推进每一笔交易。",
    ),
    "home.hero_subtitle": t("EU-zu-MENA-Marktplatz für Überbestände und Liquidation", "سوق فائض المخزون والتصفية من الاتحاد الأوروبي إلى منطقة الشرق الأوسط وشمال أفريقيا", "AB'den MENA'ya fazla stok ve tasfiye pazaryeri", "بازار مازاد و تصفیه از اروپا به منا", "Marketplace UE vers MENA pour surstocks et liquidation", "Marketplace UE a MENA de sobrestock y liquidacion", "Marketplace UE para MENA de excedentes e liquidacao", "EU-naar-MENA marketplace voor overstock en liquidatie", "欧盟到中东和北非的积压与清仓市场"),
    "home.hero_title": t(
        "Der Marktplatz für EU-Überbestände und MENA-Nachfrage.",
        "السوق الخاص بفائض مخزون الاتحاد الأوروبي وطلب منطقة الشرق الأوسط وشمال أفريقيا.",
        "AB fazla stogu ve MENA talebi icin pazaryeri.",
        "بازار مازاد اتحادیه اروپا و تقاضای منطقه منا.",
        "La marketplace pour les surstocks europeens et la demande MENA.",
        "El marketplace para sobrestock europeo y demanda MENA.",
        "O marketplace para excedentes da UE e procura MENA.",
        "De marktplaats voor EU-overstock en MENA-vraag.",
        "面向欧盟过剩库存和中东北非需求的市场平台。",
    ),
    "home.how_section_description": t("Vier Schritte für den Handelsstart", "أربع خطوات لبدء التجارة", "Ticarete baslamak icin dort adim", "چهار گام برای شروع تجارت", "Quatre etapes pour commencer a commercer", "Cuatro pasos para empezar a comerciar", "Quatro passos para comecar a negociar", "Vier stappen om te starten met handelen", "开始交易的四个步骤"),
    "home.how_section_eyebrow": t("Einfacher Ablauf", "عملية بسيطة", "Basit surec", "فرآیند ساده", "Processus simple", "Proceso simple", "Processo simples", "Eenvoudig proces", "简单流程"),
    "home.how_section_title": t("So funktioniert der Marktplatz", "كيف يعمل السوق", "Pazaryeri nasil calisir", "بازار چگونه کار می کند", "Comment fonctionne la marketplace", "Como funciona el marketplace", "Como funciona o marketplace", "Hoe de marketplace werkt", "市场如何运作"),
    "home.how_step_1_description": t(
        "Suchen Sie genehmigte Stocklots oder veröffentlichen Sie ein RFQ, wenn Sie bestimmte Spezifikationen oder Mengen benötigen.",
        "ابحث عن مخزونات معتمدة أو انشر طلب شراء عندما تحتاج إلى مواصفات أو كميات محددة.",
        "Belirli ozelliklere veya hacme ihtiyaciniz oldugunda onayli stok partilerini arayin veya bir RFQ yayinlayin.",
        "استاک لات های تاییدشده را جستجو کنید یا وقتی به مشخصات یا حجم خاصی نیاز دارید یک RFQ ثبت کنید.",
        "Recherchez des lots de stock approuves ou publiez un RFQ lorsque vous avez besoin de specifications ou de volumes precis.",
        "Busque lotes de stock aprobados o publique un RFQ cuando necesite especificaciones o volumen concretos.",
        "Procure lotes de stock aprovados ou publique um RFQ quando precisar de especificacoes ou volume especificos.",
        "Zoek naar goedgekeurde stocklots of plaats een RFQ wanneer u specifieke specificaties of volumes nodig heeft.",
        "搜索已批准的尾货批次，或在您需要特定规格或数量时发布 RFQ。",
    ),
    "home.how_step_1_title": t("Durchsuchen oder posten", "تصفح أو انشر", "Goz at veya yayinla", "مرور یا ثبت", "Parcourir ou publier", "Explorar o publicar", "Explorar ou publicar", "Bekijken of plaatsen", "浏览或发布"),
    "home.how_step_2_description": t(
        "Chatten Sie mit verifizierten Nutzern, während Identitäten verborgen bleiben, bis eine Offenlegung genehmigt wird.",
        "تحدث مع مستخدمين موثّقين بينما تبقى الهويات مخفية حتى تتم الموافقة على الكشف.",
        "Kimlik acma onaylanana kadar kimlikler gizli kalirken dogrulanmis kullanicilarla sohbet edin.",
        "با کاربران تاییدشده گفتگو کنید در حالی که هویت ها تا زمان تایید افشا پنهان می مانند.",
        "Discutez avec des utilisateurs verifies pendant que les identites restent masquees jusqu'a l'approbation de la revelation.",
        "Chatee con usuarios verificados mientras las identidades permanecen ocultas hasta que se apruebe su revelacion.",
        "Converse com utilizadores verificados enquanto as identidades permanecem ocultas ate a aprovacao da revelacao.",
        "Chat met geverifieerde gebruikers terwijl identiteiten verborgen blijven tot een onthulling is goedgekeurd.",
        "与已验证用户聊天，在揭示获批前双方身份保持隐藏。",
    ),
    "home.how_step_2_title": t("Privat verbinden", "تواصل بشكل خاص", "Ozel baglan", "اتصال خصوصی", "Se connecter en prive", "Conectar en privado", "Ligar em privado", "Privé verbinden", "私密连接"),
    "home.how_step_3_description": t(
        "Gespräche und Identitätsfreigaben werden moderiert, bevor wichtige Handelsschritte vorangehen.",
        "تتم مراجعة المحادثات وطلبات كشف الهوية قبل انتقال خطوات التجارة الأساسية إلى الأمام.",
        "Kilit ticaret adimlari ilerlemeden once gorusmeler ve kimlik acmalari denetlenir.",
        "گفتگوها و افشای هویت پیش از پیشرفت مراحل مهم تجاری نظارت می شوند.",
        "Les conversations et les revelations d'identite sont moderees avant que les etapes commerciales importantes n'avancent.",
        "Las conversaciones y revelaciones de identidad se moderan antes de avanzar pasos comerciales clave.",
        "As conversas e revelacoes de identidade sao moderadas antes de avancarem etapas comerciais importantes.",
        "Gesprekken en identiteitsonthullingen worden gemodereerd voordat belangrijke handelsstappen doorgaan.",
        "在关键交易步骤推进前，对话和身份揭示都会经过审核。",
    ),
    "home.how_step_3_title": t("Mit Aufsicht verhandeln", "تفاوض تحت إشراف", "Gozetimle pazarlik et", "مذاکره با نظارت", "Negocier avec supervision", "Negociar con supervision", "Negociar com supervisao", "Onder toezicht onderhandelen", "在监管下谈判"),
    "home.how_step_4_description": t(
        "Beide Seiten akzeptieren, die Administration genehmigt, und der Fortschritt wird mit Status und Verlauf verfolgt.",
        "يوافق الطرفان، وتعتمد الإدارة، ويتم تتبع التقدم عبر الحالة والسجل.",
        "Her iki taraf kabul eder, yonetim onaylar ve ilerleme durum ve gecmis ile takip edilir.",
        "هر دو طرف می پذیرند، ادمین تایید می کند و پیشرفت با وضعیت و سابقه پیگیری می شود.",
        "Les deux parties acceptent, l'administration approuve et la progression est suivie avec statut et historique.",
        "Ambas partes aceptan, la administracion aprueba y el progreso se sigue con estado e historial.",
        "Ambas as partes aceitam, a administracao aprova e o progresso e acompanhado com estado e historico.",
        "Beide partijen accepteren, de admin keurt goed en de voortgang wordt gevolgd met status en historie.",
        "双方接受、管理员批准，并通过状态和历史记录跟踪进度。",
    ),
    "home.how_step_4_title": t("Deal bestätigen", "أكّد الصفقة", "Anlasmayi onayla", "معامله را تایید کن", "Confirmer la transaction", "Confirmar la operacion", "Confirmar o negocio", "Deal bevestigen", "确认交易"),
    "home.market_snapshot_active_suffix": t("aktiv", "نشط", "aktif", "فعال", "actif", "activo", "ativo", "actief", "活跃"),
    "home.market_snapshot_item_1_description": t(
        "Großvolumige Räumungsbestände von verifizierten EU-Lieferanten.",
        "مخزون تصفية بكميات كبيرة من موردين أوروبيين موثّقين.",
        "Dogrulanmis AB tedarikcilerinden yuksek hacimli tasfiye envanteri.",
        "موجودی های تخلیه با حجم بالا از تامین کنندگان تاییدشده اتحادیه اروپا.",
        "Stocks de destockage a grand volume provenant de fournisseurs verifies de l'UE.",
        "Inventario de liquidacion de alto volumen de proveedores verificados de la UE.",
        "Inventario de liquidacao em grande volume de fornecedores verificados da UE.",
        "Grootvolume-opruimvoorraad van geverifieerde EU-leveranciers.",
        "来自已验证欧盟供应商的大批量清仓库存。",
    ),
    "home.market_snapshot_item_1_eyebrow": t("Beliebter Überschuss", "فائض رائج", "Trend fazla stok", "مازاد پرتقاضا", "Surplus tendance", "Excedente en tendencia", "Excedente em alta", "Trending overschot", "热门余货"),
    "home.market_snapshot_item_1_tag": t("Flexible MOQ", "حد أدنى مرن", "Esnek MOQ", "MOQ انعطاف پذیر", "MOQ flexible", "MOQ flexible", "MOQ flexivel", "Flexibele MOQ", "起订量灵活"),
    "home.market_snapshot_item_1_title": t("Industriewerkzeuge und gemischte Paletten", "أدوات صناعية ومنصات مختلطة", "Endustriyel aletler ve karisik paletler", "ابزار صنعتی و پالت های ترکیبی", "Outils industriels et palettes mixtes", "Herramientas industriales y palets mixtos", "Ferramentas industriais e paletes mistos", "Industriële gereedschappen en gemengde pallets", "工业工具和混合托盘"),
    "home.market_snapshot_item_2_description": t(
        "Frische Mischmarkenbestände für schnellere grenzüberschreitende Deals vorbereitet.",
        "مخزون جديد متعدد العلامات التجارية مُجهز لصفقات أسرع عبر الحدود.",
        "Daha hizli sinir otesi anlasmalar icin hazirlanmis yeni karisik markali stok.",
        "موجودی تازه برندهای ترکیبی که برای معاملات سریع تر فرامرزی آماده شده است.",
        "Nouveau stock multi-marques prepare pour des transactions transfrontalieres plus rapides.",
        "Stock mixto de varias marcas preparado para operaciones transfronterizas mas rapidas.",
        "Stock misto de varias marcas preparado para negociacoes transfronteiricas mais rapidas.",
        "Verse mixed-brand voorraad voorbereid voor snellere grensoverschrijdende deals.",
        "为更快跨境交易准备的全新混合品牌库存。",
    ),
    "home.market_snapshot_item_2_eyebrow": t("Neue Liquidation", "تصفية جديدة", "Yeni tasfiye", "تصفیه جدید", "Nouvelle liquidation", "Nueva liquidacion", "Nova liquidacao", "Nieuwe liquidatie", "新近清仓"),
    "home.market_snapshot_item_2_tag": t("Schnelldreher", "سريع الحركة", "Hizli donen", "پرفروش سریع", "Rotation rapide", "Alta rotacion", "Rotacao rapida", "Snel roterend", "快速流转"),
    "home.market_snapshot_item_2_title": t("Haus- und Küchenretouren", "مرتجعات المنزل والمطبخ", "Ev ve mutfak iade urunleri", "مرجوعی های خانه و آشپزخانه", "Retours maison et cuisine", "Devoluciones de hogar y cocina", "Devolucoes de casa e cozinha", "Retouren voor huis en keuken", "家居与厨房退货品"),
    "home.market_snapshot_item_3_description": t(
        "Käufer in MENA suchen aktiv nach genehmigten EU-Beständen.",
        "المشترون في منطقة الشرق الأوسط وشمال أفريقيا يبحثون بنشاط عن مخزون أوروبي معتمد.",
        "MENA'daki alicilar aktif olarak onayli AB stogu ariyor.",
        "خریداران منطقه منا به طور فعال به دنبال موجودی تاییدشده اروپایی هستند.",
        "Les acheteurs MENA recherchent activement des stocks europeens approuves.",
        "Los compradores de MENA buscan activamente stock aprobado de la UE.",
        "Os compradores MENA procuram ativamente stock aprovado da UE.",
        "Kopers in MENA zijn actief op zoek naar goedgekeurde EU-voorraad.",
        "中东和北非买家正在积极寻找已批准的欧盟库存。",
    ),
    "home.market_snapshot_item_3_eyebrow": t("Aktive RFQs", "طلبات شراء نشطة", "Aktif RFQ'lar", "RFQهای فعال", "RFQ actives", "RFQ activos", "RFQs ativas", "Actieve RFQ's", "活跃 RFQ"),
    "home.market_snapshot_item_3_tag": t("Jetzt antworten", "رد الآن", "Simdi yanitla", "اکنون پاسخ بده", "Repondre maintenant", "Responder ahora", "Responder agora", "Reageer nu", "立即响应"),
    "home.market_snapshot_item_3_title": t("Elektronik-Restposten", "شحنات تصفية إلكترونيات", "Elektronik tasfiye partileri", "محموله های تسویه الکترونیک", "Lots de liquidation electronique", "Lotes de liquidacion de electronica", "Lotes de liquidacao de eletronica", "Elektronica-opruimpartijen", "电子产品清仓批次"),
    "home.market_snapshot_title": t("Marktübersicht", "لقطة السوق", "Pazar gorunumu", "نمای بازار", "Apercu du marche", "Panorama del mercado", "Resumo do mercado", "Marktoverzicht", "市场概览"),
    "home.market_snapshot_view_all": t("Alle Listings ansehen", "عرض كل العروض", "Tum ilanlari gor", "مشاهده همه فهرست ها", "Voir toutes les annonces", "Ver todos los listados", "Ver todas as listagens", "Bekijk alle vermeldingen", "查看所有列表"),
    "home.marketplace_all": t("Alle", "الكل", "Tum", "همه", "Tous", "Todos", "Todos", "Alles", "全部"),
    "home.marketplace_categories_title": t("Kategorien", "الفئات", "Kategoriler", "دسته ها", "Categories", "Categorias", "Categorias", "Categorieen", "分类"),
    "home.marketplace_condition_title": t("Zustand", "الحالة", "Durum", "وضعیت", "Etat", "Condicion", "Condicao", "Conditie", "状态"),
    "home.marketplace_empty_state": t("Noch keine Listings.", "لا توجد عروض بعد.", "Henuz ilan yok.", "هنوز فهرستی وجود ندارد.", "Aucune annonce pour le moment.", "Aun no hay listados.", "Ainda nao existem listagens.", "Nog geen vermeldingen.", "暂无列表。"),
    "home.marketplace_filters_title": t("Filter", "الفلاتر", "Filtreler", "فیلترها", "Filtres", "Filtros", "Filtros", "Filters", "筛选"),
    "home.marketplace_open_full": t("Kompletten Marktplatz öffnen", "افتح السوق الكامل", "Tam pazaryerini ac", "بازار کامل را باز کن", "Ouvrir la marketplace complete", "Abrir marketplace completo", "Abrir marketplace completo", "Volledige marketplace openen", "打开完整市场"),
    "home.marketplace_reset": t("Zurücksetzen", "إعادة تعيين", "Sifirla", "بازنشانی", "Reinitialiser", "Restablecer", "Repor", "Resetten", "重置"),
    "home.marketplace_saved_listings": t("Gespeicherte Listings", "العروض المحفوظة", "Kaydedilen ilanlar", "فهرست های ذخیره شده", "Annonces enregistrees", "Listados guardados", "Listagens guardadas", "Opgeslagen vermeldingen", "已保存列表"),
    "home.marketplace_section_description": t(
        "Durchsuchen Sie genehmigte öffentliche Listings, die zu Ihrer ausgewählten Sprache passen.",
        "تصفح العروض العامة المعتمدة التي تطابق لغتك المختارة.",
        "Sectiginiz dile uyan onayli herkese acik ilanlari inceleyin.",
        "فهرست های عمومی تاییدشده متناسب با زبان انتخابی خود را مرور کنید.",
        "Parcourez les annonces publiques approuvees qui correspondent a votre langue selectionnee.",
        "Explore listados publicos aprobados que coincidan con su idioma seleccionado.",
        "Explore listagens publicas aprovadas que correspondam ao idioma selecionado.",
        "Bekijk goedgekeurde openbare vermeldingen die passen bij uw geselecteerde taal.",
        "浏览与您所选语言匹配的已批准公开列表。",
    ),
    "home.marketplace_section_title": t("Marktplatz", "السوق", "Pazaryeri", "بازار", "Marketplace", "Marketplace", "Marketplace", "Marketplace", "市场"),
    "home.marketplace_shortcuts_title": t("Schnellzugriffe", "اختصارات", "Kisayollar", "میانبرها", "Raccourcis", "Accesos directos", "Atalhos", "Snelkoppelingen", "快捷入口"),
    "home.marketplace_sign_in_to_save": t("Zum Speichern anmelden", "سجل الدخول للحفظ", "Kaydetmek icin giris yap", "برای ذخیره وارد شوید", "Connectez-vous pour enregistrer", "Inicie sesion para guardar", "Inicie sessao para guardar", "Log in om op te slaan", "登录后保存"),
    "home.rfq_cta_primary": t("Ein RFQ veröffentlichen", "انشر طلب شراء", "Bir RFQ yayinla", "یک RFQ ثبت کن", "Publier un RFQ", "Publicar un RFQ", "Publicar um RFQ", "Een RFQ plaatsen", "发布 RFQ"),
    "home.rfq_cta_secondary": t("RFQs entdecken", "استكشف طلبات الشراء", "RFQ'lari kesfet", "RFQها را بررسی کن", "Explorer les RFQ", "Explorar RFQ", "Explorar RFQs", "RFQ's ontdekken", "探索 RFQ"),
    "home.rfq_section_description": t(
        "Veröffentlichen Sie ein RFQ und laden Sie verifizierte Verkäufer ein, privat zu antworten.",
        "انشر طلب شراء وادعُ البائعين الموثقين للرد بشكل خاص.",
        "Bir RFQ yayinlayin ve dogrulanmis saticilari ozel olarak yanit vermeye davet edin.",
        "یک RFQ ثبت کنید و فروشندگان تاییدشده را برای پاسخ خصوصی دعوت کنید.",
        "Publiez un RFQ et invitez des vendeurs verifies a repondre en prive.",
        "Publique un RFQ e invite a vendedores verificados a responder en privado.",
        "Publique um RFQ e convide vendedores verificados a responder em privado.",
        "Plaats een RFQ en nodig geverifieerde verkopers uit om privé te reageren.",
        "发布 RFQ，并邀请已验证卖家私下回复。",
    ),
    "home.rfq_section_title": t("Suchen Sie etwas Bestimmtes?", "هل تحتاج شيئاً محدداً؟", "Belirli bir seye mi ihtiyaciniz var?", "دنبال چیز مشخصی هستید؟", "Vous cherchez quelque chose de precis ?", "Necesita algo especifico?", "Precisa de algo especifico?", "Zoekt u iets specifieks?", "您在寻找特定商品吗？"),
    "home.trust_point_1_description": t(
        "Admin-verifizierte Konten plus Käufer- und Verkäuferprüfungen vor sensiblen Aktionen.",
        "حسابات موثّقة من الإدارة بالإضافة إلى فحوصات المشترين والبائعين قبل الإجراءات الحساسة.",
        "Hassas adimlardan once yonetici tarafindan dogrulanmis hesaplar ve alici-satici kontrolleri.",
        "حساب های تاییدشده توسط ادمین همراه با بررسی خریدار و فروشنده پیش از اقدامات حساس.",
        "Comptes verifies par l'admin ainsi que controles acheteur et vendeur avant les actions sensibles.",
        "Cuentas verificadas por admin mas controles de compradores y vendedores antes de acciones sensibles.",
        "Contas verificadas pelo admin mais verificacoes de compradores e vendedores antes de acoes sensiveis.",
        "Door admin geverifieerde accounts plus controles van koper en verkoper voor gevoelige acties.",
        "管理员验证账户，并在敏感操作前进行买卖双方检查。",
    ),
    "home.trust_point_1_title": t("Verifizierte Nutzer", "مستخدمون موثّقون", "Dogrulanmis kullanicilar", "کاربران تاییدشده", "Utilisateurs verifies", "Usuarios verificados", "Utilizadores verificados", "Geverifieerde gebruikers", "已验证用户"),
    "home.trust_point_2_description": t(
        "Nur genehmigte, aktive öffentliche Inhalte sind für das richtige Sprachpublikum sichtbar.",
        "لا يظهر إلا المحتوى العام النشط والمعتمد للجمهور اللغوي المناسب.",
        "Yalnizca onayli ve aktif herkese acik icerik dogru dil kitlesine gosterilir.",
        "فقط محتوای عمومی فعال و تاییدشده برای مخاطب زبانی درست قابل مشاهده است.",
        "Seul le contenu public approuve et actif est visible pour le bon public linguistique.",
        "Solo el contenido publico aprobado y activo es visible para la audiencia linguistica correcta.",
        "Apenas o conteudo publico aprovado e ativo e visivel para a audiencia linguistica certa.",
        "Alleen goedgekeurde en actieve publieke content is zichtbaar voor het juiste taalpubliek.",
        "只有已批准且活跃的公开内容才会展示给对应语言受众。",
    ),
    "home.trust_point_2_title": t("Genehmigte Listings und RFQs", "عروض وطلبات شراء معتمدة", "Onayli ilanlar ve RFQ'lar", "فهرست ها و RFQهای تاییدشده", "Annonces et RFQ approuves", "Listados y RFQ aprobados", "Listagens e RFQs aprovados", "Goedgekeurde vermeldingen en RFQ's", "已批准的列表和 RFQ"),
    "home.trust_point_3_description": t(
        "Käufer- und Verkäuferidentitäten bleiben verborgen, bis Offenlegungsanfragen genehmigt werden.",
        "تبقى هويات المشترين والبائعين مخفية حتى تتم الموافقة على طلبات الكشف.",
        "Alici ve satici kimlikleri, aciga cikarma talepleri onaylanana kadar gizli kalir.",
        "هویت خریدار و فروشنده تا زمان تایید درخواست افشا پنهان می ماند.",
        "Les identites des acheteurs et des vendeurs restent masquees jusqu'a l'approbation des demandes de revelation.",
        "Las identidades de compradores y vendedores permanecen ocultas hasta que se aprueban las solicitudes de revelacion.",
        "As identidades de compradores e vendedores permanecem ocultas ate a aprovacao dos pedidos de revelacao.",
        "Identiteiten van kopers en verkopers blijven verborgen totdat onthullingsverzoeken zijn goedgekeurd.",
        "买家和卖家身份会一直隐藏，直到揭示请求获批。",
    ),
    "home.trust_point_3_title": t("Identitätsschutz", "حماية الهوية", "Kimlik korumasi", "حفاظت از هویت", "Protection de l'identite", "Proteccion de identidad", "Protecao de identidade", "Identiteitsbescherming", "身份保护"),
    "home.trust_point_4_description": t(
        "Deals bewegen sich in Phasen mit Admin-Aufsicht, Verlauf und Benachrichtigungen.",
        "تتحرك الصفقات عبر مراحل مع إشراف الإدارة والسجل والإشعارات.",
        "Anlasmalar yonetici gozetimi, gecmis ve bildirimlerle asamalar halinde ilerler.",
        "معاملات در مراحل مختلف همراه با نظارت ادمین، سابقه و اعلان ها پیش می روند.",
        "Les transactions avancent par etapes avec supervision admin, historique et notifications.",
        "Las operaciones avanzan por etapas con supervision de admin, historial y notificaciones.",
        "Os negocios avancam por etapas com supervisao do admin, historico e notificacoes.",
        "Deals verlopen in fasen met admin-toezicht, historie en meldingen.",
        "交易在管理员监管、历史记录和通知的支持下分阶段推进。",
    ),
    "home.trust_point_4_title": t("Kontrollierter Deal-Flow", "تدفق صفقات مضبوط", "Kontrollu anlasma akisi", "جریان کنترل شده معامله", "Flux de transaction controle", "Flujo de operaciones controlado", "Fluxo de negociacao controlado", "Gecontroleerde dealflow", "受控交易流程"),
    "home.trust_section_eyebrow": t("Vertrauen und Sicherheit", "الثقة والسلامة", "Guven ve emniyet", "اعتماد و ایمنی", "Confiance et securite", "Confianza y seguridad", "Confianca e seguranca", "Vertrouwen en veiligheid", "信任与安全"),
    "home.trust_section_title": t("Verifizierung und Aufsicht integriert", "التحقق والإشراف مدمجان", "Dogrulama ve gozetim yerlesik", "تایید و نظارت در دل پلتفرم", "Verification et supervision integrees", "Verificacion y supervision integradas", "Verificacao e supervisao integradas", "Verificatie en toezicht ingebouwd", "内置验证与监管"),
}


def fill_cms_translations(apps, schema_editor):
    CMSBlock = apps.get_model("core", "CMSBlock")

    for block in CMSBlock.objects.filter(key__in=CMS_TRANSLATIONS):
        values = CMS_TRANSLATIONS[block.key]
        for field_name, value in values.items():
            setattr(block, field_name, value)
        block.save(update_fields=[*LANGUAGE_FIELDS, "updated_at"])


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_fill_cms_footer_languages"),
    ]

    operations = [
        migrations.RunPython(fill_cms_translations, noop),
    ]
