# Generated by Django 5.2.12 on 2026-04-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_support_cms_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS · About',
                'verbose_name_plural': 'CMS · About',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='ContactCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS · Contact',
                'verbose_name_plural': 'CMS · Contact',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='FooterCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS · Footer',
                'verbose_name_plural': 'CMS · Footer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='HomepageCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS · Homepage',
                'verbose_name_plural': 'CMS · Homepage',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='ImpressumCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS · Impressum',
                'verbose_name_plural': 'CMS · Impressum',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='PrivacyCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS · Privacy',
                'verbose_name_plural': 'CMS · Privacy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='SharedCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS · Shared / Global',
                'verbose_name_plural': 'CMS · Shared / Global',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='TermsCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS · Terms',
                'verbose_name_plural': 'CMS · Terms',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
    ]
