# Generated by Django 5.2.12 on 2026-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_blog_cms_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS - Account',
                'verbose_name_plural': 'CMS - Account',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='BlogCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS - Blog',
                'verbose_name_plural': 'CMS - Blog',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='ChatCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS - Chat',
                'verbose_name_plural': 'CMS - Chat',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='DashboardCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS - Dashboard',
                'verbose_name_plural': 'CMS - Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='DealCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS - Deals',
                'verbose_name_plural': 'CMS - Deals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='InboxCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS - Inbox',
                'verbose_name_plural': 'CMS - Inbox',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='ListingUICMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS - Listing UI',
                'verbose_name_plural': 'CMS - Listing UI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='NavigationCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS - Navigation',
                'verbose_name_plural': 'CMS - Navigation',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='NotificationsCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS - Notifications',
                'verbose_name_plural': 'CMS - Notifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='RFQUICMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS - RFQ UI',
                'verbose_name_plural': 'CMS - RFQ UI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='SavedCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS - Saved',
                'verbose_name_plural': 'CMS - Saved',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.CreateModel(
            name='SupportCMSBlock',
            fields=[
            ],
            options={
                'verbose_name': 'CMS - Support',
                'verbose_name_plural': 'CMS - Support',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cmsblock',),
        ),
        migrations.AlterField(
            model_name='cmsblock',
            name='page',
            field=models.CharField(choices=[('home', 'Homepage'), ('about', 'About'), ('account', 'Account'), ('blog', 'Blog'), ('chat', 'Chat'), ('contact', 'Contact'), ('dashboard', 'Dashboard'), ('deal', 'Deals'), ('inbox', 'Inbox'), ('listing_ui', 'Listing UI'), ('nav', 'Navigation'), ('notifications', 'Notifications'), ('privacy', 'Privacy'), ('rfq_ui', 'RFQ UI'), ('saved', 'Saved'), ('support', 'Support'), ('terms', 'Terms'), ('impressum', 'Impressum'), ('footer', 'Footer'), ('shared', 'Shared / Global')], default='shared', max_length=20, verbose_name='page'),
        ),
    ]
