from django.db import migrations


def t(en, de, ar, tr, fa, fr, es, pt, nl, zh):
    return {
        "text_en": en,
        "text_de": de,
        "text_ar": ar,
        "text_tr": tr,
        "text_fa": fa,
        "text_fr": fr,
        "text_es": es,
        "text_pt": pt,
        "text_nl": nl,
        "text_zh": zh,
    }


def block(page, en, de, ar, tr, fa, fr, es, pt, nl, zh):
    payload = {"page": page, "is_active": True}
    payload.update(t(en, de, ar, tr, fa, fr, es, pt, nl, zh))
    return payload


CMS_BLOCKS = {}

CMS_BLOCKS.update(
    {
        "blog.list_page_title": block("blog", "Blog and news", "Blog und Neuigkeiten", "المدونة والأخبار", "Blog ve haberler", "وبلاگ و اخبار", "Blog et actualites", "Blog y noticias", "Blog e noticias", "Blog en nieuws", "博客与新闻"),
        "blog.list_meta_description": block("blog", "Read market news, trading guides, and platform updates.", "Lesen Sie Marktnews, Handelsleitfaden und Plattform-Updates.", "اقرأ أخبار السوق وأدلة التجارة وتحديثات المنصة.", "Pazar haberlerini, ticaret rehberlerini ve platform guncellemelerini okuyun.", "اخبار بازار، راهنماهای تجارت و به روزرسانی های پلتفرم را بخوانید.", "Lisez les actualites du marche, les guides et les mises a jour.", "Lee noticias del mercado, guias y actualizaciones de la plataforma.", "Leia noticias do mercado, guias e atualizacoes da plataforma.", "Lees marktnieuws, handleidingen en platformupdates.", "阅读市场新闻、交易指南和平台更新。"),
        "blog.list_eyebrow": block("blog", "Insights and updates", "Einblicke und Updates", "رؤى وتحديثات", "Icgoruler ve guncellemeler", "بینش ها و به روزرسانی ها", "Analyses et mises a jour", "Ideas y actualizaciones", "Insights e atualizacoes", "Inzichten en updates", "洞察与更新"),
        "blog.list_hero_title": block("blog", "News, guides, and practical trade knowledge.", "News, Leitfaden und praktisches Handelswissen.", "أخبار وأدلة ومعرفة تجارية عملية.", "Haberler, rehberler ve pratik ticaret bilgisi.", "اخبار، راهنماها و دانش عملی تجارت.", "Actualites, guides et savoir pratique du commerce.", "Noticias, guias y conocimiento practico de comercio.", "Noticias, guias e conhecimento pratico de comercio.", "Nieuws, gidsen en praktische handelskennis.", "新闻、指南和实用贸易知识。"),
        "blog.list_hero_body": block("blog", "Use the blog to stay current on marketplace activity, sourcing ideas, and product flows.", "Nutzen Sie den Blog fur Marktaktivitat, Beschaffungsideen und Warenstrome.", "استخدم المدونة لمتابعة نشاط السوق وأفكار التوريد وتدفقات المنتجات.", "Blogu pazar hareketleri, tedarik fikirleri ve urun akislarini takip etmek icin kullanin.", "از وبلاگ برای دنبال کردن فعالیت بازار، ایده های تامین و جریان کالا استفاده کنید.", "Utilisez le blog pour suivre l'activite du marche, les idees d'approvisionnement et les flux produits.", "Usa el blog para seguir la actividad del mercado, ideas de abastecimiento y flujos de producto.", "Use o blog para acompanhar a atividade do mercado, ideias de sourcing e fluxos de produto.", "Gebruik de blog om marktactiviteit, sourcingideeen en productstromen te volgen.", "通过博客了解市场动态、采购思路和产品流向。"),
        "blog.search_label": block("blog", "Search articles", "Artikel suchen", "ابحث في المقالات", "Makale ara", "جستجوی مقاله", "Rechercher des articles", "Buscar articulos", "Pesquisar artigos", "Artikelen zoeken", "搜索文章"),
        "blog.search_placeholder": block("blog", "Search by title or topic", "Nach Titel oder Thema suchen", "ابحث بالعنوان أو الموضوع", "Baslik veya konu ile ara", "بر اساس عنوان یا موضوع جستجو کنید", "Rechercher par titre ou sujet", "Buscar por titulo o tema", "Pesquisar por titulo ou tema", "Zoek op titel of onderwerp", "按标题或主题搜索"),
        "blog.all_article_types": block("blog", "All article types", "Alle Beitragstypen", "كل أنواع المقالات", "Tum yazi turleri", "همه نوع مقاله", "Tous les types d'article", "Todos los tipos de articulo", "Todos os tipos de artigo", "Alle artikeltypen", "全部文章类型"),
        "blog.apply_button": block("blog", "Apply", "Anwenden", "تطبيق", "Uygula", "اعمال", "Appliquer", "Aplicar", "Aplicar", "Toepassen", "应用"),
        "blog.reset_button": block("blog", "Reset", "Zurucksetzen", "إعادة تعيين", "Sifirla", "بازنشانی", "Reinitialiser", "Restablecer", "Redefinir", "Resetten", "重置"),
        "blog.views_label": block("blog", "views", "Aufrufe", "مشاهدات", "goruntuleme", "بازدید", "vues", "vistas", "visualizacoes", "weergaven", "浏览"),
        "blog.likes_label": block("blog", "likes", "Likes", "إعجابات", "begeni", "پسند", "likes", "me gusta", "curtidas", "likes", "点赞"),
        "blog.read_article": block("blog", "Read article", "Artikel lesen", "اقرأ المقال", "Makaleyi oku", "خواندن مقاله", "Lire l'article", "Leer articulo", "Ler artigo", "Artikel lezen", "阅读文章"),
        "blog.previous": block("blog", "Previous", "Zuruck", "السابق", "Onceki", "قبلی", "Precedent", "Anterior", "Anterior", "Vorige", "上一页"),
        "blog.next": block("blog", "Next", "Weiter", "التالي", "Sonraki", "بعدی", "Suivant", "Siguiente", "Seguinte", "Volgende", "下一页"),
        "blog.page_label": block("blog", "Page", "Seite", "الصفحة", "Sayfa", "صفحه", "Page", "Pagina", "Pagina", "Pagina", "第"),
        "blog.page_of": block("blog", "of", "von", "من", " / ", "از", "sur", "de", "de", "van", "页，共"),
        "blog.empty_title": block("blog", "No articles found", "Keine Artikel gefunden", "لم يتم العثور على مقالات", "Makale bulunamadi", "مقاله ای پیدا نشد", "Aucun article trouve", "No se encontraron articulos", "Nenhum artigo encontrado", "Geen artikelen gevonden", "未找到文章"),
        "blog.empty_body": block("blog", "Try another topic or clear the filters to see more published posts.", "Versuchen Sie ein anderes Thema oder entfernen Sie die Filter.", "جرّب موضوعًا آخر أو امسح الفلاتر لعرض المزيد من المقالات المنشورة.", "Baska bir konu deneyin veya filtreleri temizleyin.", "موضوع دیگری را امتحان کنید یا فیلترها را پاک کنید.", "Essayez un autre sujet ou supprimez les filtres.", "Prueba otro tema o limpia los filtros.", "Tente outro tema ou limpe os filtros.", "Probeer een ander onderwerp of wis de filters.", "尝试其他主题或清除筛选条件。"),
        "blog.breadcrumb_blog": block("blog", "Blog", "Blog", "المدونة", "Blog", "وبلاگ", "Blog", "Blog", "Blog", "Blog", "博客"),
        "blog.like_article": block("blog", "Like article", "Artikel liken", "أعجبني المقال", "Makaleyi begen", "پسندیدن مقاله", "Aimer l'article", "Me gusta el articulo", "Curtir artigo", "Artikel liken", "点赞文章"),
        "blog.liked": block("blog", "Liked", "Gelikt", "تم الإعجاب", "Begenildi", "پسند شد", "Aime", "Te gusta", "Curtido", "Geliked", "已点赞"),
        "blog.more_from_topic": block("blog", "More from this topic", "Mehr zu diesem Thema", "المزيد من هذا الموضوع", "Bu konudan daha fazlasi", "مطالب بیشتر از این موضوع", "Plus sur ce sujet", "Mas sobre este tema", "Mais deste tema", "Meer over dit onderwerp", "更多相关内容"),
        "blog.back_to_blog": block("blog", "Back to blog", "Zuruck zum Blog", "العودة إلى المدونة", "Bloga don", "بازگشت به وبلاگ", "Retour au blog", "Volver al blog", "Voltar ao blog", "Terug naar blog", "返回博客"),
    }
)

CMS_BLOCKS.update(
    {
        "listing_ui.eyebrow": block("listing_ui", "Seller workspace", "Verkauferbereich", "مساحة البائع", "Satici alani", "فضای فروشنده", "Espace vendeur", "Espacio del vendedor", "Espaco do vendedor", "Verkopersruimte", "卖家工作区"),
        "listing_ui.my_listings_page_title": block("listing_ui", "My listings", "Meine Angebote", "عروضي", "Ilanlarim", "آگهی های من", "Mes offres", "Mis anuncios", "Meus anuncios", "Mijn listings", "我的商品"),
        "listing_ui.my_listings_page_intro": block("listing_ui", "Track every stocklot, status update, and seller action from one page.", "Verfolgen Sie jedes Angebot, jeden Status und jede Aktion an einem Ort.", "تابع كل عرض وتحديث حالة وإجراء من صفحة واحدة.", "Tum ilanlari, durumlari ve islemleri tek sayfadan yonetin.", "همه آگهی ها، وضعیت ها و اقدام ها را از یک صفحه دنبال کنید.", "Suivez chaque offre, statut et action depuis une page unique.", "Controla cada anuncio, estado y accion desde una sola pagina.", "Acompanhe cada anuncio, status e acao em uma pagina.", "Beheer elke listing, status en actie vanaf een pagina.", "在一个页面中跟踪每个商品、状态和操作。"),
        "listing_ui.add_listing": block("listing_ui", "Create listing", "Angebot erstellen", "أنشئ عرضًا", "Ilan olustur", "ایجاد آگهی", "Creer une offre", "Crear anuncio", "Criar anuncio", "Listing maken", "创建商品"),
        "listing_ui.view_marketplace": block("listing_ui", "View marketplace", "Marktplatz ansehen", "عرض السوق", "Pazari gor", "مشاهده بازار", "Voir le marketplace", "Ver mercado", "Ver marketplace", "Marketplace bekijken", "查看市场"),
        "listing_ui.my_listings_overview_title": block("listing_ui", "Listing overview", "Angebotsuberblick", "نظرة عامة على العروض", "Ilan genel gorunumu", "مرور آگهی ها", "Vue d'ensemble des offres", "Resumen de anuncios", "Visao geral dos anuncios", "Listingoverzicht", "商品概览"),
        "listing_ui.my_listings_overview_body": block("listing_ui", "Keep your company, stocklots, and seller readiness in one clear view.", "Behalten Sie Firma, Angebote und Verkaufsbereitschaft im Blick.", "اجعل الشركة والعروض وجاهزية البيع في عرض واضح واحد.", "Sirketinizi, ilanlarinizi ve satici hazirliginizi tek ekranda tutun.", "شرکت، آگهی ها و آمادگی فروش را در یک نمای روشن ببینید.", "Gardez entreprise, offres et preparation vendeur dans une vue claire.", "Mantén empresa, anuncios y preparacion del vendedor en una sola vista.", "Mantenha empresa, anuncios e prontidao do vendedor em uma unica vista.", "Houd bedrijf, listings en verkopersstatus in een duidelijke weergave.", "在一个清晰视图中查看公司、商品和卖家准备情况。"),
        "listing_ui.company_metric_body": block("listing_ui", "Your active seller company for marketplace publishing.", "Ihre aktive Verkaufsfirma fur den Marktplatz.", "شركة البائع النشطة للنشر في السوق.", "Pazaryeri yayinlari icin aktif satici sirketiniz.", "شرکت فعال فروشنده شما برای انتشار در بازار.", "Votre entreprise vendeur active pour publier.", "Tu empresa vendedora activa para publicar.", "Sua empresa vendedora ativa para publicar.", "Uw actieve verkopersbedrijf voor publicatie.", "你用于发布市场内容的活跃卖家公司。"),
        "listing_ui.total_listings_body": block("listing_ui", "A quick count of every stocklot tied to your account.", "Eine schnelle Zahl aller Angebote in Ihrem Konto.", "عدد سريع لكل العروض المرتبطة بحسابك.", "Hesabiniza bagli tum ilanlarin hizli sayimi.", "تعداد سریع همه آگهی های متصل به حساب شما.", "Un compte rapide de toutes vos offres.", "Conteo rapido de todos tus anuncios.", "Contagem rapida de todos os seus anuncios.", "Een snelle telling van al uw listings.", "与你账户关联的全部商品数量。"),
        "listing_ui.seller_status_body": block("listing_ui", "Check whether your account can publish and receive inquiries.", "Prufen Sie, ob Ihr Konto veroffentlichen und Anfragen empfangen kann.", "تحقق مما إذا كان حسابك يمكنه النشر واستقبال الاستفسارات.", "Hesabinizin yayin yapip mesaj alabilecegini kontrol edin.", "بررسی کنید آیا حساب شما می تواند منتشر کند و پیام بگیرد.", "Verifiez si votre compte peut publier et recevoir des demandes.", "Comprueba si tu cuenta puede publicar y recibir consultas.", "Verifique se sua conta pode publicar e receber consultas.", "Controleer of uw account kan publiceren en aanvragen ontvangen.", "检查你的账户是否可以发布并接收询问。"),
        "listing_ui.your_listings_title": block("listing_ui", "Your listing queue", "Ihre Angebotsliste", "قائمة عروضك", "Ilan sirasi", "صف آگهی های شما", "Votre file d'offres", "Tu cola de anuncios", "Sua fila de anuncios", "Uw lijst met listings", "你的商品列表"),
        "listing_ui.your_listings_body": block("listing_ui", "Open, edit, pause, or close each stocklot from this list.", "Offnen, bearbeiten, pausieren oder schliessen Sie jedes Angebot hier.", "افتح أو عدّل أو أوقف أو أغلق كل عرض من هذه القائمة.", "Her ilani bu listeden acin, duzenleyin, durdurun veya kapatin.", "هر آگهی را از این فهرست باز، ویرایش، متوقف یا بسته کنید.", "Ouvrez, modifiez, mettez en pause ou fermez chaque offre ici.", "Abre, edita, pausa o cierra cada anuncio desde aqui.", "Abra, edite, pause ou encerre cada anuncio aqui.", "Open elk verzoek om details te bewerken, status te bekijken of gesprekken te lezen.", "在此列表中打开、编辑、暂停或关闭每个商品。"),
        "listing_ui.empty_my_listings_title": block("listing_ui", "No listings yet", "Noch keine Angebote", "لا توجد عروض بعد", "Henuz ilan yok", "هنوز آگهی ندارید", "Aucune offre pour le moment", "Aun no tienes anuncios", "Nenhum anuncio ainda", "Nog geen listings", "还没有商品"),
        "listing_ui.empty_my_listings_body": block("listing_ui", "Add your first stocklot to start receiving marketplace visibility and buyer interest.", "Fugen Sie Ihr erstes Angebot hinzu, um Sichtbarkeit und Interesse zu erhalten.", "أضف أول عرض لبدء الظهور وجذب اهتمام المشترين.", "Gorunurluk ve alici ilgisi icin ilk ilaninizi ekleyin.", "اولین آگهی را اضافه کنید تا دیده شوید و توجه خریداران را بگیرید.", "Ajoutez votre premiere offre pour obtenir de la visibilite.", "Agrega tu primer anuncio para empezar a recibir visibilidad.", "Adicione seu primeiro anuncio para ganhar visibilidade.", "Voeg uw eerste listing toe om zichtbaar te worden.", "添加你的第一条商品以获得曝光和买家关注。"),
        "listing_ui.create_first_listing": block("listing_ui", "Add first listing", "Erstes Angebot erstellen", "أضف أول عرض", "Ilk ilani ekle", "افزودن اولین آگهی", "Ajouter la premiere offre", "Agregar primer anuncio", "Adicionar primeiro anuncio", "Eerste listing toevoegen", "添加第一条商品"),
        "listing_ui.marketplace_page_title": block("listing_ui", "Marketplace", "Marktplatz", "السوق", "Pazar yeri", "بازار", "Marketplace", "Mercado", "Marketplace", "Marktplaats", "市场"),
        "listing_ui.marketplace_meta_description": block("listing_ui", "Browse approved stocklots that match your selected language and filters.", "Durchsuchen Sie freigegebene Angebote passend zu Sprache und Filtern.", "تصفح العروض المعتمدة المطابقة للغتك وفلاترك.", "Secili dilinize ve filtrelerinize uyan onayli ilanlara goz atin.", "آگهی های تاییدشده مطابق زبان و فیلترهای خود را ببینید.", "Parcourez les offres approuvees selon votre langue et vos filtres.", "Explora anuncios aprobados segun tu idioma y filtros.", "Explore anuncios aprovados conforme seu idioma e filtros.", "Bekijk goedgekeurde listings volgens uw taal en filters.", "浏览符合所选语言和筛选条件的已批准商品。"),
        "listing_ui.marketplace_eyebrow": block("listing_ui", "Live marketplace", "Live-Marktplatz", "السوق المباشر", "Canli pazar yeri", "بازار زنده", "Marketplace en direct", "Mercado en vivo", "Marketplace ao vivo", "Live marketplace", "实时市场"),
        "listing_ui.marketplace_hero_title": block("listing_ui", "Explore active stocklots with clear trade context.", "Entdecken Sie aktive Angebote mit klarem Handelskontekst.", "استكشف العروض النشطة مع سياق تجاري واضح.", "Acik ticaret baglami ile aktif ilanlari kesfedin.", "آگهی های فعال را با زمینه روشن تجاری بررسی کنید.", "Explorez des offres actives avec un contexte commercial clair.", "Explora lotes activos con contexto comercial claro.", "Explore lotes ativos com contexto comercial claro.", "Verken actieve listings met duidelijke handelscontext.", "探索具有清晰交易背景的活跃商品。"),
        "listing_ui.marketplace_hero_body": block("listing_ui", "Filter by category, quantity, condition, and location to find the right commercial lot faster.", "Filtern Sie nach Kategorie, Menge, Zustand und Standort fur schneller passende Angebote.", "صفِّ حسب الفئة والكمية والحالة والموقع للعثور على العرض المناسب أسرع.", "Dogru ticari partiye daha hizli ulasmak icin kategori, miktar, durum ve konuma gore filtreleyin.", "برای یافتن سریع تر محموله مناسب بر اساس دسته، مقدار، وضعیت و موقعیت فیلتر کنید.", "Filtrez par categorie, quantite, etat et lieu pour trouver le bon lot plus vite.", "Filtra por categoria, cantidad, estado y ubicacion para encontrar el lote adecuado.", "Filtre por categoria, quantidade, estado e localizacao para achar o lote certo.", "Filter op categorie, hoeveelheid, conditie en locatie om sneller de juiste partij te vinden.", "按类别、数量、成色和地点筛选，更快找到合适的货盘。"),
        "listing_ui.visible_listings_body": block("listing_ui", "Only language-ready and approved listings appear in this count.", "Hier erscheinen nur sprachbereite und freigegebene Angebote.", "يظهر هنا فقط عدد العروض المعتمدة والمتاحة بهذه اللغة.", "Bu sayida yalnizca dil uyumlu ve onayli ilanlar yer alir.", "فقط آگهی های تاییدشده و آماده این زبان در این تعداد دیده می شوند.", "Ce total montre uniquement les offres approuvees et disponibles.", "Aqui solo aparecen anuncios aprobados y disponibles en este idioma.", "Aqui so aparecem anuncios aprovados e disponiveis neste idioma.", "Hier staan alleen goedgekeurde en taalklare listings.", "此数量仅包含当前语言可见且已批准的商品。"),
        "listing_ui.workflow_title": block("listing_ui", "Guided trade flow", "Gefuhrter Handelsablauf", "تدفق تجارة موجّه", "Yonlendirilmis ticaret akisi", "جریان هدایت شده معامله", "Flux commercial guide", "Flujo comercial guiado", "Fluxo comercial guiado", "Begeleide handelsflow", "引导式交易流程"),
        "listing_ui.workflow_body": block("listing_ui", "Review stocklots, contact verified sellers, and move to a controlled deal process.", "Prufen Sie Angebote, kontaktieren Sie verifizierte Verkaufer und gehen Sie in den Deal-Prozess.", "راجع العروض وتواصل مع البائعين الموثقين وانتقل إلى عملية صفقة مضبوطة.", "Ilanlari inceleyin, dogrulanmis saticilarla iletisime gecin ve kontrollu isleme ilerleyin.", "آگهی ها را بررسی کنید، با فروشندگان تاییدشده تماس بگیرید و به روند کنترل شده معامله بروید.", "Examinez les offres, contactez des vendeurs verifies et avancez vers un deal controle.", "Revisa anuncios, contacta vendedores verificados y pasa a un proceso controlado.", "Revise anuncios, fale com vendedores verificados e avance para um processo controlado.", "Bekijk listings, neem contact op met geverifieerde verkopers en ga naar een gecontroleerd dealproces.", "查看商品、联系已验证卖家，并进入受控交易流程。"),
        "listing_ui.available_stocklots_title": block("listing_ui", "Available stocklots", "Verfugbare Angebote", "العروض المتاحة", "Mevcut stok partileri", "محصولات موجود", "Lots disponibles", "Lotes disponibles", "Lotes disponiveis", "Beschikbare stocklots", "可用货盘"),
        "listing_ui.live_marketplace_inventory": block("listing_ui", "Live marketplace inventory ready for review.", "Live-Marktplatzinventar bereit zur Prufung.", "مخزون السوق المباشر جاهز للمراجعة.", "Canli pazar envanteri incelemeye hazir.", "موجودی زنده بازار برای بررسی آماده است.", "Inventaire du marketplace pret a etre consulte.", "Inventario del mercado listo para revisar.", "Inventario do marketplace pronto para revisar.", "Live marketplace-voorraad klaar om te bekijken.", "实时市场库存可供查看。"),
        "listing_ui.filters": block("listing_ui", "Filters", "Filter", "الفلاتر", "Filtreler", "فیلترها", "Filtres", "Filtros", "Filtros", "Filters", "筛选"),
        "listing_ui.refine_results_title": block("listing_ui", "Refine results", "Ergebnisse verfeinern", "حسّن النتائج", "Sonuclari daralt", "نتایج را دقیق تر کنید", "Affiner les resultats", "Refinar resultados", "Refinar resultados", "Resultaten verfijnen", "优化结果"),
        "listing_ui.refine_results_body": block("listing_ui", "Use the controls to narrow the inventory to the lots you can actually trade.", "Nutzen Sie die Steuerung, um die Auswahl auf wirklich handelbare Angebote zu verengen.", "استخدم الأدوات لتضييق المخزون إلى العروض التي يمكنك فعلاً تداولها.", "Kontrolleri kullanarak gercekten ticaret yapabileceginiz ilanlara odaklanin.", "از کنترل ها استفاده کنید تا فقط روی آگهی های قابل معامله تمرکز کنید.", "Utilisez les controles pour cibler les lots vraiment pertinents.", "Usa los controles para reducir el inventario a los lotes utiles.", "Use os controles para focar nos lotes relevantes.", "Gebruik de filters om de voorraad te beperken tot relevante partijen.", "使用筛选器将范围缩小到真正可交易的货盘。"),
        "listing_ui.reset": block("listing_ui", "Reset", "Zurucksetzen", "إعادة تعيين", "Sifirla", "بازنشانی", "Reinitialiser", "Restablecer", "Redefinir", "Resetten", "重置"),
        "listing_ui.apply_filters": block("listing_ui", "Apply filters", "Filter anwenden", "طبّق الفلاتر", "Filtreleri uygula", "اعمال فیلترها", "Appliquer les filtres", "Aplicar filtros", "Aplicar filtros", "Filters toepassen", "应用筛选"),
        "listing_ui.reset_filters": block("listing_ui", "Reset filters", "Filter zurucksetzen", "إعادة ضبط الفلاتر", "Filtreleri sifirla", "بازنشانی فیلترها", "Reinitialiser les filtres", "Restablecer filtros", "Redefinir filtros", "Filters resetten", "重置筛选"),
        "listing_ui.contact_seller": block("listing_ui", "Contact seller", "Verkaufer kontaktieren", "تواصل مع البائع", "Satici iletisime gec", "تماس با فروشنده", "Contacter le vendeur", "Contactar vendedor", "Contactar vendedor", "Contact opnemen met verkoper", "联系卖家"),
        "listing_ui.contact_seller_verification_required": block("listing_ui", "Buyer verification required", "Kauferverifizierung erforderlich", "مطلوب توثيق المشتري", "Alici dogrulamasi gerekli", "تایید خریدار لازم است", "Verification acheteur requise", "Se requiere verificacion del comprador", "Verificacao do comprador obrigatoria", "Kopersverificatie vereist", "需要买家验证"),
        "listing_ui.seller_label": block("listing_ui", "Seller", "Verkaufer", "البائع", "Satici", "فروشنده", "Vendeur", "Vendedor", "Vendedor", "Verkoper", "卖家"),
        "listing_ui.files_documents": block("listing_ui", "Files and documents", "Dateien und Dokumente", "الملفات والمستندات", "Dosyalar ve belgeler", "فایل ها و اسناد", "Fichiers et documents", "Archivos y documentos", "Arquivos e documentos", "Bestanden en documenten", "文件与资料"),
        "listing_ui.no_files_available": block("listing_ui", "No files available", "Keine Dateien verfugbar", "لا توجد ملفات متاحة", "Dosya yok", "فایلی موجود نیست", "Aucun fichier disponible", "No hay archivos disponibles", "Nenhum arquivo disponivel", "Geen bestanden beschikbaar", "没有可用文件"),
        "listing_ui.description_label": block("listing_ui", "Description", "Beschreibung", "الوصف", "Aciklama", "توضیحات", "Description", "Descripcion", "Descricao", "Beschrijving", "描述"),
        "listing_ui.useful_links": block("listing_ui", "Useful links", "Nutzliche Links", "روابط مفيدة", "Faydali baglantilar", "لینک های مفید", "Liens utiles", "Enlaces utiles", "Links uteis", "Handige links", "有用链接"),
    }
)

CMS_BLOCKS.update(
    {
        "rfq_ui.buyer_eyebrow": block("rfq_ui", "Buyer workspace", "Kauferbereich", "مساحة المشتري", "Alici alani", "فضای خریدار", "Espace acheteur", "Espacio del comprador", "Espaco do comprador", "Kopersruimte", "买家工作区"),
        "rfq_ui.my_rfqs_page_title": block("rfq_ui", "My RFQs", "Meine RFQs", "طلباتي", "RFQ'lerim", "درخواست های من", "Mes RFQ", "Mis RFQ", "Meus RFQ", "Mijn RFQ's", "我的询价"),
        "rfq_ui.my_rfqs_page_intro": block("rfq_ui", "Track the buyer requests you have published and keep supplier responses organized.", "Verfolgen Sie veroffentlichte Anfragen und halten Sie Antworten geordnet.", "تابع طلبات الشراء التي نشرتها وحافظ على تنظيم ردود الموردين.", "Yayinladiginiz talepleri izleyin ve tedarikci yanitlarini duzenli tutun.", "درخواست های منتشرشده را دنبال کنید و پاسخ تامین کنندگان را منظم نگه دارید.", "Suivez vos demandes publiees et gardez les reponses organisees.", "Sigue tus solicitudes publicadas y mantén las respuestas ordenadas.", "Acompanhe seus pedidos publicados e mantenha as respostas organizadas.", "Volg uw geplaatste RFQ's en houd reacties geordend.", "跟踪你发布的询价，并保持供应商回复有序。"),
        "rfq_ui.create_rfq": block("rfq_ui", "Post RFQ", "RFQ einstellen", "انشر طلب شراء", "RFQ yayinla", "ثبت درخواست", "Publier un RFQ", "Publicar RFQ", "Publicar RFQ", "RFQ plaatsen", "发布询价"),
        "rfq_ui.browse_rfqs": block("rfq_ui", "Browse RFQs", "RFQs durchsuchen", "تصفح الطلبات", "RFQ'leri gez", "مرور درخواست ها", "Parcourir les RFQ", "Explorar RFQ", "Explorar RFQ", "RFQ's bekijken", "浏览询价"),
        "rfq_ui.my_rfqs_overview_title": block("rfq_ui", "RFQ overview", "RFQ-Uberblick", "نظرة عامة على الطلبات", "RFQ genel gorunumu", "مرور درخواست ها", "Vue d'ensemble RFQ", "Resumen de RFQ", "Visao geral de RFQ", "RFQ-overzicht", "询价概览"),
        "rfq_ui.my_rfqs_overview_body": block("rfq_ui", "See how many requests are open, under review, or already attracting responses.", "Sehen Sie, wie viele Anfragen offen, in Prufung oder beantwortet sind.", "اعرف كم طلبًا مفتوحًا أو قيد المراجعة أو تلقى ردودًا بالفعل.", "Acik, incelemede veya yanit alan talepleri gorun.", "ببینید چه تعداد درخواست باز، در حال بررسی یا دارای پاسخ است.", "Voyez combien de demandes sont ouvertes, en revue ou deja repondues.", "Mira cuantas solicitudes estan abiertas, en revision o con respuestas.", "Veja quantos pedidos estao abertos, em revisao ou com respostas.", "Bekijk hoeveel verzoeken openstaan, in controle zijn of al reacties hebben.", "查看有多少请求处于开放、审核中或已收到回复。"),
        "rfq_ui.my_rfqs_metric_body": block("rfq_ui", "Only approved and language-ready RFQs become visible to suppliers.", "Nur freigegebene und sprachbereite RFQs werden fur Lieferanten sichtbar.", "فقط الطلبات المعتمدة والمتاحة بهذه اللغة تظهر للموردين.", "Yalnizca onayli ve dil uyumlu RFQ'ler tedarikcilere gorunur.", "فقط درخواست های تاییدشده و آماده زبان برای تامین کنندگان دیده می شوند.", "Seuls les RFQ approuves et disponibles sont visibles aux fournisseurs.", "Solo los RFQ aprobados y listos por idioma son visibles.", "Somente RFQs aprovados e disponiveis ficam visiveis.", "Alleen goedgekeurde en taalklare RFQ's zijn zichtbaar.", "只有已批准且适用于该语言的询价会对供应商可见。"),
        "rfq_ui.buyer_workspace_title": block("rfq_ui", "Buyer workspace", "Kauferbereich", "مساحة المشتري", "Alici alani", "فضای خریدار", "Espace acheteur", "Espacio comprador", "Espaco do comprador", "Kopersruimte", "买家工作区"),
        "rfq_ui.buyer_workspace_body": block("rfq_ui", "Use this area to publish demand, compare replies, and move toward a deal.", "Nutzen Sie diesen Bereich, um Bedarf zu posten, Antworten zu vergleichen und zum Deal zu gehen.", "استخدم هذه المساحة لنشر الطلب ومقارنة الردود والانتقال نحو صفقة.", "Talep yayinlamak, yanitlari karsilastirmak ve anlasmaya gitmek icin bu alani kullanin.", "از این بخش برای اعلام تقاضا، مقایسه پاسخ ها و حرکت به سمت معامله استفاده کنید.", "Utilisez cet espace pour publier la demande et comparer les reponses.", "Usa esta area para publicar demanda y comparar respuestas.", "Use esta area para publicar demanda e comparar respostas.", "Gebruik dit deel om vraag te plaatsen en reacties te vergelijken.", "用这个区域发布需求、比较回复并推进交易。"),
        "rfq_ui.your_rfqs_title": block("rfq_ui", "Your buyer requests", "Ihre Anfragen", "طلبات الشراء الخاصة بك", "Talepleriniz", "درخواست های شما", "Vos demandes d'achat", "Tus solicitudes de compra", "Seus pedidos de compra", "Uw koopverzoeken", "你的采购请求"),
        "rfq_ui.your_rfqs_body": block("rfq_ui", "Open each request to edit details, review status, or read supplier conversations.", "Offnen Sie jede Anfrage zum Bearbeiten, Prufen oder Lesen von Gesprachen.", "افتح كل طلب لتعديل التفاصيل أو مراجعة الحالة أو قراءة محادثات الموردين.", "Her talebi duzenlemek, durumu gormek veya konusmalari okumak icin acin.", "برای ویرایش جزئیات، بررسی وضعیت یا خواندن گفتگوها هر درخواست را باز کنید.", "Ouvrez chaque demande pour modifier, verifier le statut ou lire les echanges.", "Abre cada solicitud para editar, revisar estado o leer conversaciones.", "Abra cada pedido para editar, revisar status ou ler conversas.", "Open elk verzoek om details te bewerken, status te bekijken of gesprekken te lezen.", "打开每个请求以编辑详情、查看状态或阅读供应商对话。"),
        "rfq_ui.empty_my_rfqs_title": block("rfq_ui", "No RFQs yet", "Noch keine RFQs", "لا توجد طلبات بعد", "Henuz RFQ yok", "هنوز درخواستی ندارید", "Aucun RFQ pour le moment", "Aun no tienes RFQ", "Nenhum RFQ ainda", "Nog geen RFQ's", "还没有询价"),
        "rfq_ui.empty_my_rfqs_body": block("rfq_ui", "Post your first buying request so suppliers can see what you need.", "Stellen Sie Ihre erste Anfrage ein, damit Lieferanten Ihren Bedarf sehen.", "انشر أول طلب شراء لكي يرى الموردون ما تحتاجه.", "Ihtiyacinizi gostermek icin ilk RFQ'nuzu yayinlayin.", "اولین درخواست خرید خود را ثبت کنید تا تامین کنندگان نیاز شما را ببینند.", "Publiez votre premiere demande pour montrer votre besoin aux fournisseurs.", "Publica tu primera solicitud para que los proveedores vean tu necesidad.", "Publique seu primeiro pedido para que fornecedores vejam sua demanda.", "Plaats uw eerste RFQ zodat leveranciers uw vraag zien.", "发布你的第一条询价，让供应商看到你的需求。"),
        "rfq_ui.browse_page_title": block("rfq_ui", "RFQ marketplace", "RFQ-Marktplatz", "سوق الطلبات", "RFQ pazari", "بازار درخواست ها", "Marketplace RFQ", "Mercado RFQ", "Marketplace de RFQ", "RFQ-marktplaats", "询价市场"),
        "rfq_ui.browse_meta_description": block("rfq_ui", "Browse public buyer requests that are approved and available in your selected language.", "Durchsuchen Sie offentliche, freigegebene RFQs in Ihrer gewahlten Sprache.", "تصفح طلبات الشراء العامة المعتمدة والمتاحة بلغتك المختارة.", "Secili dilinizde mevcut, herkese acik ve onayli alici taleplerini inceleyin.", "درخواست های عمومی تاییدشده و موجود در زبان انتخابی خود را ببینید.", "Parcourez les demandes publiques approuvees disponibles dans votre langue.", "Explora solicitudes publicas aprobadas en tu idioma seleccionado.", "Explore pedidos publicos aprovados no idioma selecionado.", "Bekijk openbare goedgekeurde RFQ's in uw gekozen taal.", "浏览你所选语言下可见的公开已批准询价。"),
        "rfq_ui.browse_eyebrow": block("rfq_ui", "Open demand", "Offene Nachfrage", "الطلب المفتوح", "Acil talep", "تقاضای باز", "Demande ouverte", "Demanda abierta", "Demanda aberta", "Open vraag", "公开需求"),
        "rfq_ui.browse_hero_title": block("rfq_ui", "Find live buyer demand you can answer quickly.", "Finden Sie aktive Nachfrage, auf die Sie schnell antworten konnen.", "اعثر على طلب شراء حي يمكنك الرد عليه بسرعة.", "Hizli yanit verebileceginiz canli alici taleplerini bulun.", "تقاضای زنده خریداران را پیدا کنید که بتوانید سریع پاسخ دهید.", "Trouvez une demande acheteur active a laquelle repondre vite.", "Encuentra demanda activa de compradores para responder rapido.", "Encontre demanda ativa de compradores para responder rapido.", "Vind live kopersvraag waarop u snel kunt reageren.", "找到你可以快速响应的实时买家需求。"),
        "rfq_ui.browse_hero_body": block("rfq_ui", "Use the public RFQ feed to discover real buyer need, review scope, and open a direct conversation.", "Nutzen Sie den offentlichen RFQ-Feed, um Bedarf zu entdecken und ein Gesprach zu starten.", "استخدم تغذية الطلبات العامة لاكتشاف الحاجة الفعلية وفتح محادثة مباشرة.", "Gercek alici ihtiyacini kesfetmek ve gorusme acmak icin RFQ akislarini kullanin.", "از فید عمومی درخواست ها برای یافتن نیاز واقعی خریدار و آغاز گفتگو استفاده کنید.", "Utilisez le flux RFQ public pour decouvrir la demande reelle et ouvrir une conversation.", "Usa el feed publico de RFQ para descubrir demanda real y abrir una conversacion.", "Use o feed publico de RFQ para descobrir demanda real e abrir conversa.", "Gebruik de openbare RFQ-feed om echte vraag te vinden en een gesprek te openen.", "通过公开询价流发现真实买家需求并开启直接对话。"),
        "rfq_ui.post_rfq": block("rfq_ui", "Post RFQ", "RFQ einstellen", "انشر طلب شراء", "RFQ yayinla", "ثبت درخواست", "Publier un RFQ", "Publicar RFQ", "Publicar RFQ", "RFQ plaatsen", "发布询价"),
        "rfq_ui.browse_marketplace": block("rfq_ui", "Browse marketplace", "Marktplatz durchsuchen", "تصفح السوق", "Pazaryerini gez", "مرور بازار", "Parcourir le marketplace", "Explorar mercado", "Explorar marketplace", "Marketplace bekijken", "浏览市场"),
        "rfq_ui.open_rfqs_body": block("rfq_ui", "This count reflects only RFQs visible in your current language.", "Diese Zahl zeigt nur in Ihrer Sprache sichtbare RFQs.", "هذا العدد يعكس فقط الطلبات المرئية بلغتك الحالية.", "Bu sayi yalnizca mevcut dilinizde gorunen RFQ'leri gosterir.", "این تعداد فقط درخواست های قابل مشاهده در زبان فعلی شما را نشان می دهد.", "Ce total ne montre que les RFQ visibles dans votre langue.", "Este total solo refleja RFQ visibles en tu idioma actual.", "Essa contagem mostra apenas RFQs visiveis no idioma atual.", "Deze telling toont alleen RFQ's zichtbaar in uw huidige taal.", "此数量仅显示你当前语言可见的询价。"),
        "rfq_ui.for_sellers_title": block("rfq_ui", "Made for suppliers", "Fur Lieferanten", "مخصص للموردين", "Tedarikciler icin", "برای تامین کنندگان", "Concu pour les fournisseurs", "Hecho para proveedores", "Feito para fornecedores", "Voor leveranciers", "面向供应商"),
        "rfq_ui.for_sellers_body": block("rfq_ui", "Open a request, qualify the buyer, and decide whether to start a trade conversation.", "Offnen Sie eine Anfrage, qualifizieren Sie den Kaufer und entscheiden Sie uber das Gesprach.", "افتح الطلب، قيّم المشتري، وقرّر ما إذا كنت ستبدأ محادثة تجارية.", "Talebi acin, aliciyi degerlendirin ve gorusme baslatip baslatmayacaginiza karar verin.", "درخواست را باز کنید، خریدار را ارزیابی کنید و درباره شروع گفتگو تصمیم بگیرید.", "Ouvrez une demande, qualifiez l'acheteur et decidez d'engager une conversation.", "Abre una solicitud, valida al comprador y decide si iniciar una conversacion.", "Abra um pedido, avalie o comprador e decida se inicia uma conversa.", "Open een verzoek, beoordeel de koper en beslis of u een gesprek start.", "打开请求、评估买家，并决定是否开始交易对话。"),
        "rfq_ui.search_placeholder": block("rfq_ui", "Search RFQs by keyword", "RFQs per Stichwort suchen", "ابحث في الطلبات بكلمة مفتاحية", "Anahtar kelime ile RFQ ara", "درخواست ها را با کلیدواژه جستجو کنید", "Rechercher des RFQ par mot-cle", "Buscar RFQ por palabra clave", "Pesquisar RFQ por palavra-chave", "Zoek RFQ's op trefwoord", "按关键词搜索询价"),
        "rfq_ui.search": block("rfq_ui", "Search", "Suchen", "بحث", "Ara", "جستجو", "Rechercher", "Buscar", "Pesquisar", "Zoeken", "搜索"),
        "rfq_ui.reset": block("rfq_ui", "Reset", "Zurucksetzen", "إعادة تعيين", "Sifirla", "بازنشانی", "Reinitialiser", "Restablecer", "Redefinir", "Resetten", "重置"),
        "rfq_ui.active_requests_title": block("rfq_ui", "Active requests", "Aktive Anfragen", "الطلبات النشطة", "Aktif talepler", "درخواست های فعال", "Demandes actives", "Solicitudes activas", "Pedidos ativos", "Actieve verzoeken", "活跃请求"),
        "rfq_ui.active_requests_body": block("rfq_ui", "Review demand that is currently open for supplier responses.", "Prufen Sie Bedarf, der aktuell fur Antworten offen ist.", "راجع الطلب المفتوح حاليًا لردود الموردين.", "Su anda tedarikci yanitlarina acik talepleri inceleyin.", "تقاضای باز برای پاسخ تامین کنندگان را بررسی کنید.", "Examinez la demande actuellement ouverte aux fournisseurs.", "Revisa la demanda abierta a respuestas de proveedores.", "Revise a demanda aberta a respostas de fornecedores.", "Bekijk vraag die momenteel openstaat voor reacties.", "查看当前开放给供应商响应的需求。"),
        "rfq_ui.empty_browse_title": block("rfq_ui", "No RFQs match this view", "Keine RFQs passen zu dieser Ansicht", "لا توجد طلبات مطابقة لهذا العرض", "Bu gorunumle eslesen RFQ yok", "درخواستی برای این نما پیدا نشد", "Aucun RFQ ne correspond a cette vue", "No hay RFQ para esta vista", "Nenhum RFQ corresponde a esta visualizacao", "Geen RFQ's passen bij deze weergave", "没有符合此视图的询价"),
        "rfq_ui.empty_browse_body": block("rfq_ui", "Try a broader keyword or come back when more buyer demand is published in this language.", "Versuchen Sie ein breiteres Stichwort oder kommen Sie spater wieder.", "جرّب كلمة أوسع أو عد لاحقًا عندما تُنشر طلبات أكثر بهذه اللغة.", "Daha genis bir kelime deneyin veya daha fazla talep yayinlandiginda tekrar gelin.", "کلیدواژه گسترده تری امتحان کنید یا بعدا بازگردید.", "Essayez un mot plus large ou revenez plus tard.", "Prueba una palabra mas amplia o vuelve mas tarde.", "Tente uma palavra mais ampla ou volte depois.", "Probeer een ruimer trefwoord of kom later terug.", "尝试更宽泛的关键词或稍后再来。"),
        "rfq_ui.detail_intro": block("rfq_ui", "Review the request carefully before sending a quote or opening a direct conversation.", "Prufen Sie die Anfrage sorgfaltig, bevor Sie ein Angebot senden.", "راجع الطلب بعناية قبل إرسال عرض أو بدء محادثة مباشرة.", "Teklif gondermeden once talebi dikkatle inceleyin.", "پیش از ارسال قیمت یا شروع گفتگو، درخواست را با دقت بررسی کنید.", "Examinez bien la demande avant d'envoyer une offre.", "Revisa la solicitud antes de enviar una cotizacion.", "Revise o pedido antes de enviar uma proposta.", "Bekijk het verzoek goed voordat u een offerte stuurt.", "发送报价或开始对话前请仔细查看该请求。"),
        "rfq_ui.saved_rfq": block("rfq_ui", "Saved RFQ", "Gespeichertes RFQ", "طلب محفوظ", "Kaydedildi", "درخواست ذخیره شد", "RFQ enregistre", "RFQ guardado", "RFQ salvo", "Opgeslagen RFQ", "已保存询价"),
        "rfq_ui.save_rfq": block("rfq_ui", "Save RFQ", "RFQ speichern", "احفظ الطلب", "RFQ kaydet", "ذخیره درخواست", "Enregistrer le RFQ", "Guardar RFQ", "Salvar RFQ", "RFQ opslaan", "保存询价"),
        "rfq_ui.quantity_label": block("rfq_ui", "Quantity", "Menge", "الكمية", "Miktar", "مقدار", "Quantite", "Cantidad", "Quantidade", "Hoeveelheid", "数量"),
        "rfq_ui.budget_label": block("rfq_ui", "Budget", "Budget", "الميزانية", "Butce", "بودجه", "Budget", "Presupuesto", "Orcamento", "Budget", "预算"),
        "rfq_ui.open_budget": block("rfq_ui", "Open budget", "Offenes Budget", "ميزانية مفتوحة", "Acik butce", "بودجه باز", "Budget ouvert", "Presupuesto abierto", "Orcamento aberto", "Open budget", "预算开放"),
        "rfq_ui.destination_label": block("rfq_ui", "Destination", "Zielort", "الوجهة", "Hedef", "مقصد", "Destination", "Destino", "Destino", "Bestemming", "目的地"),
        "rfq_ui.buyer_label": block("rfq_ui", "Buyer", "Kaufer", "المشتري", "Alici", "خریدار", "Acheteur", "Comprador", "Comprador", "Koper", "买家"),
        "rfq_ui.verified_buyer": block("rfq_ui", "Verified buyer", "Verifizierter Kaufer", "مشتري موثّق", "Dogrulanmis alici", "خریدار تاییدشده", "Acheteur verifie", "Comprador verificado", "Comprador verificado", "Geverifieerde koper", "已验证买家"),
        "rfq_ui.buyer_visible_on_request": block("rfq_ui", "Buyer details available on request", "Kauferdetails auf Anfrage", "تفاصيل المشتري متاحة عند الطلب", "Alici bilgileri talep uzerine", "جزئیات خریدار در صورت درخواست", "Details acheteur sur demande", "Datos del comprador bajo solicitud", "Dados do comprador sob solicitacao", "Koperdetails op aanvraag", "买家详情可按需提供"),
        "rfq_ui.send_quote": block("rfq_ui", "Send quote", "Angebot senden", "أرسل عرضًا", "Teklif gonder", "ارسال قیمت", "Envoyer une offre", "Enviar cotizacion", "Enviar proposta", "Offerte sturen", "发送报价"),
        "rfq_ui.ask_question": block("rfq_ui", "Ask question", "Frage stellen", "اطرح سؤالاً", "Soru sor", "پرسیدن سوال", "Poser une question", "Hacer una pregunta", "Fazer pergunta", "Vraag stellen", "提问"),
        "rfq_ui.send_quote_verification_required": block("rfq_ui", "Buyer verification required to quote", "Kauferverifizierung fur Angebote erforderlich", "توثيق المشتري مطلوب لإرسال العرض", "Teklif icin alici dogrulamasi gerekli", "برای ارسال قیمت تایید خریدار لازم است", "Verification acheteur requise pour repondre", "Se requiere verificacion para cotizar", "Verificacao do comprador obrigatoria para cotar", "Kopersverificatie vereist om te offreren", "发送报价前需要买家验证"),
        "rfq_ui.ask_question_verification_required": block("rfq_ui", "Buyer verification required to message", "Kauferverifizierung fur Nachrichten erforderlich", "توثيق المشتري مطلوب للمراسلة", "Mesaj icin alici dogrulamasi gerekli", "برای پیام دادن تایید خریدار لازم است", "Verification acheteur requise pour envoyer un message", "Se requiere verificacion para enviar mensaje", "Verificacao do comprador obrigatoria para enviar mensagem", "Kopersverificatie vereist om te berichten", "发送消息前需要买家验证"),
        "rfq_ui.rfq_closed": block("rfq_ui", "RFQ closed", "RFQ geschlossen", "الطلب مغلق", "RFQ kapali", "درخواست بسته است", "RFQ ferme", "RFQ cerrado", "RFQ fechado", "RFQ gesloten", "询价已关闭"),
        "rfq_ui.request_details_title": block("rfq_ui", "Request details", "Anfragedetails", "تفاصيل الطلب", "Talep ayrintilari", "جزئیات درخواست", "Details de la demande", "Detalles de la solicitud", "Detalhes do pedido", "Verzoekdetails", "请求详情"),
        "rfq_ui.request_details_body": block("rfq_ui", "Review the buyer scope, specification, and commercial context before replying.", "Prufen Sie Umfang, Spezifikation und Kontext vor Ihrer Antwort.", "راجع نطاق الطلب والمواصفات والسياق التجاري قبل الرد.", "Yanittan once kapsam, spesifikasyon ve ticari baglami inceleyin.", "پیش از پاسخ، دامنه، مشخصات و زمینه تجاری را بررسی کنید.", "Examinez le besoin, la specification et le contexte avant de repondre.", "Revisa alcance, especificacion y contexto comercial antes de responder.", "Revise escopo, especificacao e contexto comercial antes de responder.", "Bekijk omvang, specificatie en context voordat u antwoordt.", "回复前请查看需求范围、规格和商业背景。"),
        "rfq_ui.files_trade_documents": block("rfq_ui", "Files and trade documents", "Dateien und Handelsdokumente", "الملفات ووثائق التجارة", "Dosyalar ve ticaret belgeleri", "فایل ها و اسناد تجاری", "Fichiers et documents commerciaux", "Archivos y documentos comerciales", "Arquivos e documentos comerciais", "Bestanden en handelsdocumenten", "文件和贸易资料"),
        "rfq_ui.files_trade_documents_body": block("rfq_ui", "Attached files help suppliers understand scope and requirements faster.", "Angehangte Dateien helfen Lieferanten beim schnellen Verstehen.", "الملفات المرفقة تساعد الموردين على فهم المتطلبات بسرعة.", "Ekli dosyalar tedarikcilerin gereksinimleri daha hizli anlamasina yardimci olur.", "فایل های پیوست به تامین کنندگان برای درک سریع تر کمک می کنند.", "Les fichiers joints aident les fournisseurs a comprendre plus vite.", "Los archivos adjuntos ayudan a entender mejor los requisitos.", "Arquivos anexos ajudam fornecedores a entender mais rapido.", "Bijlagen helpen leveranciers sneller te begrijpen wat nodig is.", "附件可帮助供应商更快理解需求。"),
        "rfq_ui.no_files": block("rfq_ui", "No files", "Keine Dateien", "لا توجد ملفات", "Dosya yok", "بدون فایل", "Aucun fichier", "Sin archivos", "Sem arquivos", "Geen bestanden", "无文件"),
        "rfq_ui.no_files_attached": block("rfq_ui", "No files attached", "Keine Dateien angehangt", "لا توجد ملفات مرفقة", "Ekli dosya yok", "فایلی پیوست نشده", "Aucun fichier joint", "No hay archivos adjuntos", "Nenhum arquivo anexado", "Geen bestanden toegevoegd", "未附加文件"),
        "rfq_ui.no_files_attached_body": block("rfq_ui", "This request currently relies on the written brief only.", "Diese Anfrage basiert derzeit nur auf der schriftlichen Beschreibung.", "يعتمد هذا الطلب حاليًا على الوصف المكتوب فقط.", "Bu talep su anda yalnizca yazili aciklamaya dayaniyor.", "این درخواست فعلا فقط بر توضیح متنی متکی است.", "Cette demande repose pour l'instant sur la description ecrite.", "Esta solicitud por ahora depende solo de la descripcion escrita.", "Este pedido por enquanto depende apenas do texto.", "Dit verzoek steunt momenteel alleen op de beschrijving.", "此请求目前仅依赖书面说明。"),
        "rfq_ui.summary_title": block("rfq_ui", "Summary", "Zusammenfassung", "الملخص", "Ozet", "خلاصه", "Resume", "Resumen", "Resumo", "Samenvatting", "摘要"),
        "rfq_ui.posted_label": block("rfq_ui", "Posted", "Veroffentlicht", "تم النشر", "Yayinlandi", "منتشر شده", "Publie", "Publicado", "Publicado", "Geplaatst", "已发布"),
        "rfq_ui.updated_label": block("rfq_ui", "Updated", "Aktualisiert", "تم التحديث", "Guncellendi", "به روز شد", "Mis a jour", "Actualizado", "Atualizado", "Bijgewerkt", "已更新"),
        "rfq_ui.responses_label": block("rfq_ui", "Responses", "Antworten", "الردود", "Yanitlar", "پاسخ ها", "Reponses", "Respuestas", "Respostas", "Reacties", "回复数"),
        "rfq_ui.buyer_trust_label": block("rfq_ui", "Buyer trust", "Kaufervertrauen", "ثقة المشتري", "Alici guveni", "اعتماد خریدار", "Confiance acheteur", "Confianza del comprador", "Confianca do comprador", "Kopervertrouwen", "买家可信度"),
        "rfq_ui.standard_buyer_account": block("rfq_ui", "Standard buyer account", "Standard-Kauferkonto", "حساب مشتري عادي", "Standart alici hesabi", "حساب خریدار استاندارد", "Compte acheteur standard", "Cuenta de comprador estandar", "Conta padrao de comprador", "Standaard kopersaccount", "标准买家账户"),
        "rfq_ui.buyer_trust_body": block("rfq_ui", "Use verification status and conversation quality before sharing sensitive commercial detail.", "Nutzen Sie Verifizierung und Gesprachsqualitat, bevor Sie sensible Details teilen.", "استخدم حالة التوثيق وجودة المحادثة قبل مشاركة معلومات حساسة.", "Hassas ticari detaylardan once dogrulama durumunu ve gorusme kalitesini kullanin.", "پیش از اشتراک جزئیات حساس، وضعیت تایید و کیفیت گفتگو را بررسی کنید.", "Utilisez le statut de verification avant de partager des details sensibles.", "Usa el estado de verificacion antes de compartir informacion sensible.", "Use o status de verificacao antes de compartilhar detalhes sensiveis.", "Gebruik verificatiestatus voordat u gevoelige details deelt.", "在分享敏感商业信息前先查看验证状态和对话质量。"),
        "rfq_ui.response_guidance_title": block("rfq_ui", "Response guidance", "Antwortleitfaden", "إرشادات الرد", "Yanit rehberi", "راهنمای پاسخ", "Guide de reponse", "Guia de respuesta", "Guia de resposta", "Antwoordrichtlijnen", "回复指引"),
        "rfq_ui.response_guidance_point_1": block("rfq_ui", "Confirm product fit and quantity before quoting.", "Bestatigen Sie Produktfit und Menge vor dem Angebot.", "أكد ملاءمة المنتج والكمية قبل التسعير.", "Tekliften once urun uyumu ve miktari dogrulayin.", "پیش از قیمت دهی، تناسب کالا و مقدار را تایید کنید.", "Confirmez l'adaptation du produit et la quantite avant l'offre.", "Confirma el encaje del producto y la cantidad antes de cotizar.", "Confirme a adequacao do produto e a quantidade antes da proposta.", "Bevestig productfit en hoeveelheid voordat u offreert.", "报价前先确认产品匹配和数量。"),
        "rfq_ui.response_guidance_point_2": block("rfq_ui", "Use the conversation to clarify shipping, timing, and documents.", "Nutzen Sie das Gesprach fur Versand, Timing und Dokumente.", "استخدم المحادثة لتوضيح الشحن والتوقيت والمستندات.", "Sevkiyat, zamanlama ve belgeleri netlestirmek icin gorusmeyi kullanin.", "از گفتگو برای روشن کردن حمل، زمان بندی و اسناد استفاده کنید.", "Utilisez la conversation pour clarifier transport, delais et documents.", "Usa la conversacion para aclarar envio, tiempos y documentos.", "Use a conversa para esclarecer envio, prazo e documentos.", "Gebruik het gesprek om verzending, timing en documenten te verduidelijken.", "通过对话澄清运输、时间和文件要求。"),
        "rfq_ui.response_guidance_point_3": block("rfq_ui", "Move into the deal workflow only when both sides are ready.", "Gehen Sie erst in den Deal-Prozess, wenn beide Seiten bereit sind.", "انتقل إلى مسار الصفقة فقط عندما يكون الطرفان جاهزين.", "Her iki taraf hazir oldugunda anlasma surecine gecin.", "فقط زمانی وارد فرایند معامله شوید که هر دو طرف آماده باشند.", "Passez au flux deal seulement lorsque les deux parties sont pretes.", "Pasa al flujo de trato solo cuando ambas partes esten listas.", "Avance para o fluxo de negocio somente quando os dois lados estiverem prontos.", "Ga pas naar de dealflow als beide partijen klaar zijn.", "仅当双方准备就绪时再进入交易流程。"),
    }
)

CMS_BLOCKS.update(
    {
        "deal.page_eyebrow": block("deal", "Deal", "Deal", "الصفقة", "Anlasma", "معامله", "Deal", "Acuerdo", "Negocio", "Deal", "交易"),
        "deal.page_title": block("deal", "Deal detail", "Deal-Details", "تفاصيل الصفقة", "Anlasma detayi", "جزئیات معامله", "Detail du deal", "Detalle del acuerdo", "Detalhe do negocio", "Deal-detail", "交易详情"),
        "deal.page_intro": block("deal", "Review decisions, identity state, and progress history for this controlled deal.", "Prufen Sie Entscheidungen, Identitatsstatus und Verlauf fur diesen kontrollierten Deal.", "راجع القرارات وحالة الهوية وسجل التقدم لهذه الصفقة المضبوطة.", "Bu kontrollu anlasma icin kararlar, kimlik durumu ve ilerleme gecmisini inceleyin.", "تصمیم ها، وضعیت هویت و تاریخچه پیشرفت این معامله کنترل شده را بررسی کنید.", "Examinez decisions, identite et historique pour ce deal controle.", "Revisa decisiones, estado de identidad e historial de este acuerdo controlado.", "Revise decisoes, estado de identidade e historico deste negocio controlado.", "Bekijk beslissingen, identiteitsstatus en voortgang voor deze gecontroleerde deal.", "查看此受控交易的决策、身份状态和进度历史。"),
        "deal.workflow_title": block("deal", "Workflow status", "Workflow-Status", "حالة سير العمل", "Akis durumu", "وضعیت روند", "Statut du flux", "Estado del flujo", "Status do fluxo", "Workflowstatus", "流程状态"),
        "deal.updated_label": block("deal", "Updated", "Aktualisiert", "تم التحديث", "Guncellendi", "به روز شد", "Mis a jour", "Actualizado", "Atualizado", "Bijgewerkt", "已更新"),
        "deal.approve_button": block("deal", "Approve", "Genehmigen", "موافقة", "Onayla", "تایید", "Approuver", "Aprobar", "Aprovar", "Goedkeuren", "批准"),
        "deal.reject_button": block("deal", "Reject", "Ablehnen", "رفض", "Reddet", "رد", "Rejeter", "Rechazar", "Rejeitar", "Afwijzen", "拒绝"),
        "deal.cancel_button": block("deal", "Cancel", "Abbrechen", "إلغاء", "Iptal et", "لغو", "Annuler", "Cancelar", "Cancelar", "Annuleren", "取消"),
        "deal.mark_in_progress_button": block("deal", "Mark in progress", "Als in Bearbeitung markieren", "ضع كقيد التنفيذ", "Surecte isaretle", "در حال انجام", "Marquer en cours", "Marcar en progreso", "Marcar em andamento", "Markeer als actief", "标记为进行中"),
        "deal.mark_ready_button": block("deal", "Mark ready", "Als bereit markieren", "ضع كجاهز", "Hazir isaretle", "آماده علامت بزن", "Marquer pret", "Marcar listo", "Marcar pronto", "Markeer als klaar", "标记为就绪"),
        "deal.mark_completed_button": block("deal", "Mark completed", "Als abgeschlossen markieren", "ضع كمكتمل", "Tamamlandi isaretle", "تکمیل شده علامت بزن", "Marquer termine", "Marcar completado", "Marcar concluido", "Markeer als voltooid", "标记为已完成"),
        "deal.type_label": block("deal", "Type", "Typ", "النوع", "Tur", "نوع", "Type", "Tipo", "Tipo", "Type", "类型"),
        "deal.seller_user_label": block("deal", "Seller user", "Verkaufernutzer", "مستخدم البائع", "Satici kullanicisi", "کاربر فروشنده", "Utilisateur vendeur", "Usuario vendedor", "Usuario vendedor", "Verkopergebruiker", "卖家用户"),
        "deal.seller_company_label": block("deal", "Seller company", "Verkauferfirma", "شركة البائع", "Satici sirketi", "شرکت فروشنده", "Societe vendeur", "Empresa vendedora", "Empresa vendedora", "Verkopersbedrijf", "卖家公司"),
        "deal.created_label": block("deal", "Created", "Erstellt", "تم الإنشاء", "Olusturuldu", "ایجاد شد", "Cree", "Creado", "Criado", "Aangemaakt", "已创建"),
        "deal.identity_controls_title": block("deal", "Identity controls", "Identitatskontrolle", "عناصر التحكم بالهوية", "Kimlik kontrolleri", "کنترل های هویت", "Controles d'identite", "Controles de identidad", "Controles de identidade", "Identiteitscontrole", "身份控制"),
        "deal.seller_identity_title": block("deal", "Seller identity", "Verkauferidentitat", "هوية البائع", "Satici kimligi", "هویت فروشنده", "Identite vendeur", "Identidad del vendedor", "Identidade do vendedor", "Verkopersidentiteit", "卖家身份"),
        "deal.buyer_identity_title": block("deal", "Buyer identity", "Kauferidentitat", "هوية المشتري", "Alici kimligi", "هویت خریدار", "Identite acheteur", "Identidad del comprador", "Identidade do comprador", "Kopersidentiteit", "买家身份"),
        "deal.identity_revealed": block("deal", "Identity revealed", "Identitat sichtbar", "تم كشف الهوية", "Kimlik acik", "هویت آشکار شد", "Identite revelee", "Identidad revelada", "Identidade revelada", "Identiteit zichtbaar", "身份已公开"),
        "deal.identity_hidden": block("deal", "Identity hidden", "Identitat verborgen", "الهوية مخفية", "Kimlik gizli", "هویت پنهان", "Identite cachee", "Identidad oculta", "Identidade oculta", "Identiteit verborgen", "身份已隐藏"),
        "deal.visible_label": block("deal", "Visible", "Sichtbar", "مرئي", "Gorunur", "قابل مشاهده", "Visible", "Visible", "Visivel", "Zichtbaar", "可见"),
        "deal.hidden_label": block("deal", "Hidden", "Verborgen", "مخفي", "Gizli", "پنهان", "Cache", "Oculto", "Oculto", "Verborgen", "隐藏"),
        "deal.approve_seller_reveal": block("deal", "Approve seller reveal", "Verkauferfreigabe genehmigen", "وافق على كشف البائع", "Satici ifsasini onayla", "تایید نمایش فروشنده", "Approuver la revelation vendeur", "Aprobar revelacion del vendedor", "Aprovar exibicao do vendedor", "Verkoperonthulling goedkeuren", "批准卖家公开"),
        "deal.hide_seller_button": block("deal", "Hide seller", "Verkaufer verbergen", "أخفِ البائع", "Saticiyi gizle", "پنهان کردن فروشنده", "Masquer le vendeur", "Ocultar vendedor", "Ocultar vendedor", "Verkoper verbergen", "隐藏卖家"),
        "deal.approve_buyer_reveal": block("deal", "Approve buyer reveal", "Kauferfreigabe genehmigen", "وافق على كشف المشتري", "Alici ifsasini onayla", "تایید نمایش خریدار", "Approuver la revelation acheteur", "Aprobar revelacion del comprador", "Aprovar exibicao do comprador", "Koperonthulling goedkeuren", "批准买家公开"),
        "deal.hide_buyer_button": block("deal", "Hide buyer", "Kaufer verbergen", "أخفِ المشتري", "Aliciyi gizle", "پنهان کردن خریدار", "Masquer l'acheteur", "Ocultar comprador", "Ocultar comprador", "Koper verbergen", "隐藏买家"),
        "deal.history_title": block("deal", "History", "Verlauf", "السجل", "Gecmis", "تاریخچه", "Historique", "Historial", "Historico", "Geschiedenis", "历史"),
        "deal.no_history": block("deal", "No history yet.", "Noch kein Verlauf.", "لا يوجد سجل بعد.", "Henuz gecmis yok.", "هنوز تاریخچه ای نیست.", "Pas encore d'historique.", "Aun no hay historial.", "Ainda nao ha historico.", "Nog geen geschiedenis.", "暂无历史记录。"),
    }
)


def seed_platform_ui_cms_blocks(apps, schema_editor):
    CMSBlock = apps.get_model("core", "CMSBlock")
    for key, defaults in CMS_BLOCKS.items():
        CMSBlock.objects.update_or_create(key=key, defaults=defaults)


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_seed_internal_cms_blocks"),
    ]

    operations = [
        migrations.RunPython(seed_platform_ui_cms_blocks, noop),
    ]
