# Generated by Django 5.2.12 on 2026-04-12 00:00

from django.db import migrations


SEEDED_MESSAGES = [
    "Marketplace maintenance window on Sunday 02:00–03:00 UTC",
    "Wartungsfenster am Sonntag 02:00–03:00 UTC",
    "صيانة المنصة يوم الأحد من 02:00 إلى 03:00 بالتوقيت العالمي",
    "New industrial categories added: Metalworking, Construction, Printing",
    "Neue Industriekategorien: Metallbearbeitung, Bau, Druck",
    "تمت إضافة فئات صناعية جديدة: تشغيل المعادن، البناء، الطباعة",
    "Identity reveal approvals now faster: admins online 09:00–18:00 CET",
    "Identitätsfreigaben jetzt schneller: Admins online 09:00–18:00 CET",
    "الموافقة على كشف الهوية أسرع الآن: المشرفون متواجدون 09:00–18:00 بتوقيت وسط أوروبا",
]


def cleanup_ticker_sources(apps, schema_editor):
    CMSBlock = apps.get_model("core", "CMSBlock")
    TickerNews = apps.get_model("core", "TickerNews")
    TickerNewsTranslation = apps.get_model("core", "TickerNewsTranslation")

    CMSBlock.objects.filter(key__startswith="ticker.").delete()

    TickerNewsTranslation.objects.filter(message__in=SEEDED_MESSAGES).delete()
    TickerNews.objects.filter(priority__in=[30, 20, 10], link_url="").delete()


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_seed_platform_ui_cms_blocks"),
    ]

    operations = [
        migrations.RunPython(cleanup_ticker_sources, noop),
    ]
