# Generated by Django 5.2.12 on 2026-03-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0002_refactor_conversations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro')], default='EUR', max_length=10, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='unit_type',
            field=models.CharField(choices=[('piece', 'Piece'), ('carton', 'Carton'), ('pallet', 'Pallet'), ('set', 'Set'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('lot', 'Lot'), ('truckload', 'Truckload'), ('container_20ft', '20ft Container'), ('container_40ft', '40ft Container')], max_length=50, verbose_name='unit type'),
        ),
        migrations.AlterField(
            model_name='rfqmessage',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro')], default='EUR', max_length=10, verbose_name='currency'),
        ),
    ]
