# Generated by Django 5.2.12 on 2026-03-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0004_rfq_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional image or video file.', null=True, upload_to='attachments/rfq_messages/', verbose_name='attachment'),
        ),
    ]
