# Generated by Django 5.2.12 on 2026-03-30 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0005_rfqmessage_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='rfqs.rfq', verbose_name='rfq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_rfqs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'saved RFQ',
                'verbose_name_plural': 'saved RFQs',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'rfq')},
            },
        ),
    ]
