# Generated by Django 5.2.12 on 2026-03-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_verified_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified_user',
            field=models.BooleanField(default=False, help_text='Admin override: mark this account as trusted without full buyer/seller verification.', verbose_name='verified user'),
        ),
    ]
