# Generated by Django 5.2.12 on 2026-04-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_is_verified_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('en', 'English')], default='ar', max_length=2, verbose_name='preferred language'),
        ),
    ]
