from django.urls import path

from .views import (
    AboutView,
    ContactView,
    HomeView,
    NotificationListView,
    NotificationMarkAllView,
    NotificationMarkReadView,
    AdminDashboardView,
    ModerateDealView,
    ModerateRFQMessageView,
    ModerateInquiryReplyView,
    ModerateStocklotView,
    IdentityToggleView,
    ToggleUserActiveView,
    CreateVisibilityGrantView,
    RevokeVisibilityGrantView,
    UserListView,
    UserDetailView,
    UserCreateView,
    UserUpdateView,
    UserDeleteView,
    UserVerifyToggleView,
    CompanyListView,
    CompanyDetailView,
    CompanyCreateView,
    CompanyUpdateView,
    CompanyDeleteView,
    DealListView,
    DealDetailView,
    DealCreateView,
    DealUpdateView,
    DealDeleteView,
    DealProgressView,
    StocklotListView,
    StocklotDetailView,
    StocklotCreateView,
    StocklotUpdateView,
    StocklotDeleteView,
    RFQListView,
    RFQDetailView,
    RFQCreateView,
    RFQUpdateView,
    RFQDeleteView,
    RFQStatusView,
    InquiryListView,
    InquiryDetailView,
    InquiryCreateView,
    InquiryUpdateView,
    InquiryDeleteView,
    InquiryReplyListView,
    InquiryReplyDetailView,
    InquiryReplyUpdateView,
    InquiryReplyDeleteView,
    RFQMessageListView,
    RFQMessageDetailView,
    RFQMessageUpdateView,
    RFQMessageDeleteView,
    DealStatusView,
    DealIdentityRequestView,
)

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/<int:pk>/read/", NotificationMarkReadView.as_view(), name="notification_read"),
    path("notifications/read-all/", NotificationMarkAllView.as_view(), name="notification_read_all"),
    path("control/", AdminDashboardView.as_view(), name="control"),
    path("control/deal/<int:pk>/<str:decision>/", ModerateDealView.as_view(), name="control_deal"),
    path("control/rfq-message/<int:pk>/<str:decision>/", ModerateRFQMessageView.as_view(), name="control_rfq_message"),
    path("control/inquiry-reply/<int:pk>/<str:decision>/", ModerateInquiryReplyView.as_view(), name="control_inquiry_reply"),
    path("control/stocklot/<int:pk>/<str:decision>/", ModerateStocklotView.as_view(), name="control_stocklot"),
    path("control/identity/<str:model>/<int:pk>/<str:decision>/", IdentityToggleView.as_view(), name="control_identity"),
    path("control/user/<int:pk>/toggle/", ToggleUserActiveView.as_view(), name="control_user_toggle"),
    path("control/visibility/<str:direction>/", CreateVisibilityGrantView.as_view(), name="control_visibility_add"),
    path("control/visibility/<str:grant_type>/<int:pk>/revoke/", RevokeVisibilityGrantView.as_view(), name="control_visibility_revoke"),
    # CRUD control pages
    path("control/users/", UserListView.as_view(), name="control_users"),
    path("control/users/create/", UserCreateView.as_view(), name="control_user_create"),
    path("control/users/<int:pk>/", UserDetailView.as_view(), name="control_user_detail"),
    path("control/users/<int:pk>/edit/", UserUpdateView.as_view(), name="control_user_edit"),
    path("control/users/<int:pk>/delete/", UserDeleteView.as_view(), name="control_user_delete"),
    path("control/users/<int:pk>/verify/", UserVerifyToggleView.as_view(), {"action": "verify"}, name="control_user_verify"),
    path("control/users/<int:pk>/unverify/", UserVerifyToggleView.as_view(), {"action": "unverify"}, name="control_user_unverify"),

    path("control/companies/", CompanyListView.as_view(), name="control_companies"),
    path("control/companies/create/", CompanyCreateView.as_view(), name="control_company_create"),
    path("control/companies/<int:pk>/", CompanyDetailView.as_view(), name="control_company_detail"),
    path("control/companies/<int:pk>/edit/", CompanyUpdateView.as_view(), name="control_company_edit"),
    path("control/companies/<int:pk>/delete/", CompanyDeleteView.as_view(), name="control_company_delete"),

    path("control/deals/", DealListView.as_view(), name="control_deals"),
    path("control/deals/create/", DealCreateView.as_view(), name="control_deal_create"),
    path("control/deals/<int:pk>/", DealDetailView.as_view(), name="control_deal_detail"),
    path("control/deals/<int:pk>/edit/", DealUpdateView.as_view(), name="control_deal_edit"),
    path("control/deals/<int:pk>/delete/", DealDeleteView.as_view(), name="control_deal_delete"),
    path("control/deals/<int:pk>/progress/<str:action>/", DealProgressView.as_view(), name="control_deal_progress"),

    path("control/stocklots/", StocklotListView.as_view(), name="control_stocklots"),
    path("control/stocklots/create/", StocklotCreateView.as_view(), name="control_stocklot_create"),
    path("control/stocklots/<int:pk>/", StocklotDetailView.as_view(), name="control_stocklot_detail"),
    path("control/stocklots/<int:pk>/edit/", StocklotUpdateView.as_view(), name="control_stocklot_edit"),
    path("control/stocklots/<int:pk>/delete/", StocklotDeleteView.as_view(), name="control_stocklot_delete"),

    path("control/rfqs/", RFQListView.as_view(), name="control_rfqs"),
    path("control/rfqs/create/", RFQCreateView.as_view(), name="control_rfq_create"),
    path("control/rfqs/<int:pk>/", RFQDetailView.as_view(), name="control_rfq_detail"),
    path("control/rfqs/<int:pk>/edit/", RFQUpdateView.as_view(), name="control_rfq_edit"),
    path("control/rfqs/<int:pk>/delete/", RFQDeleteView.as_view(), name="control_rfq_delete"),
    path("control/rfqs/<int:pk>/<str:action>/", RFQStatusView.as_view(), name="control_rfq_status"),

    path("control/inquiries/", InquiryListView.as_view(), name="control_inquiries"),
    path("control/inquiries/create/", InquiryCreateView.as_view(), name="control_inquiry_create"),
    path("control/inquiries/<int:pk>/", InquiryDetailView.as_view(), name="control_inquiry_detail"),
    path("control/inquiries/<int:pk>/edit/", InquiryUpdateView.as_view(), name="control_inquiry_edit"),
    path("control/inquiries/<int:pk>/delete/", InquiryDeleteView.as_view(), name="control_inquiry_delete"),

    path("control/inquiry-replies/", InquiryReplyListView.as_view(), name="control_inquiry_replies_list"),
    path("control/inquiry-replies/<int:pk>/", InquiryReplyDetailView.as_view(), name="control_inquiry_reply_detail"),
    path("control/inquiry-replies/<int:pk>/edit/", InquiryReplyUpdateView.as_view(), name="control_inquiry_reply_edit"),
    path("control/inquiry-replies/<int:pk>/delete/", InquiryReplyDeleteView.as_view(), name="control_inquiry_reply_delete"),
    path("control/rfq-messages/", RFQMessageListView.as_view(), name="control_rfq_messages_list"),
    path("control/rfq-messages/<int:pk>/", RFQMessageDetailView.as_view(), name="control_rfq_message_detail"),
    path("control/rfq-messages/<int:pk>/edit/", RFQMessageUpdateView.as_view(), name="control_rfq_message_edit"),
    path("control/rfq-messages/<int:pk>/delete/", RFQMessageDeleteView.as_view(), name="control_rfq_message_delete"),
    # deal status polling
    path("deal-status/<int:pk>/", DealStatusView.as_view(), name="deal_status"),
    # deal identity requests
    path("deal-identity/<int:pk>/<str:action>/<str:target>/", DealIdentityRequestView.as_view(), name="deal_identity_request"),
]
