# Generated by Django 5.2.12 on 2026-04-03 15:37

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ar', 'Arabic'), ('tr', 'Turkish'), ('fa', 'Farsi'), ('fr', 'French'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('zh', 'Chinese')], default='en', max_length=2, verbose_name='original language')),
                ('kind', models.CharField(choices=[('news', 'News'), ('guide', 'Guide'), ('tutorial', 'Tutorial'), ('update', 'Platform update'), ('insight', 'Market insight')], default='news', max_length=20, verbose_name='content type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='slug')),
                ('body', models.TextField(verbose_name='body')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='title (English)')),
                ('body_en', models.TextField(blank=True, verbose_name='body (English)')),
                ('title_de', models.CharField(blank=True, max_length=255, verbose_name='title (German)')),
                ('body_de', models.TextField(blank=True, verbose_name='body (German)')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='title (Arabic)')),
                ('body_ar', models.TextField(blank=True, verbose_name='body (Arabic)')),
                ('title_tr', models.CharField(blank=True, max_length=255, verbose_name='title (Turkish)')),
                ('body_tr', models.TextField(blank=True, verbose_name='body (Turkish)')),
                ('title_fa', models.CharField(blank=True, max_length=255, verbose_name='title (Farsi)')),
                ('body_fa', models.TextField(blank=True, verbose_name='body (Farsi)')),
                ('title_fr', models.CharField(blank=True, max_length=255, verbose_name='title (French)')),
                ('body_fr', models.TextField(blank=True, verbose_name='body (French)')),
                ('title_es', models.CharField(blank=True, max_length=255, verbose_name='title (Spanish)')),
                ('body_es', models.TextField(blank=True, verbose_name='body (Spanish)')),
                ('title_pt', models.CharField(blank=True, max_length=255, verbose_name='title (Portuguese)')),
                ('body_pt', models.TextField(blank=True, verbose_name='body (Portuguese)')),
                ('title_nl', models.CharField(blank=True, max_length=255, verbose_name='title (Dutch)')),
                ('body_nl', models.TextField(blank=True, verbose_name='body (Dutch)')),
                ('title_zh', models.CharField(blank=True, max_length=255, verbose_name='title (Chinese)')),
                ('body_zh', models.TextField(blank=True, verbose_name='body (Chinese)')),
                ('featured_image', models.FileField(blank=True, null=True, upload_to=blog.models.article_featured_image_upload_path, verbose_name='featured image')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.article', verbose_name='article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'article like',
                'verbose_name_plural': 'article likes',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'article')},
            },
        ),
    ]
