# Generated by Django 5.2.12 on 2026-03-27 19:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklots', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='price'),
        ),
    ]
