# Generated by Django 5.2.12 on 2026-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklots', '0006_media_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklot',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('overstock', 'Overstock'), ('shelf_pull', 'Shelf Pull'), ('customer_return', 'Customer Return'), ('a_grade_return', 'A-Grade Return'), ('b_grade_return', 'B-Grade Return'), ('c_grade_return', 'C-Grade Return'), ('mixed_grade', 'Mixed Grade'), ('refurbished', 'Refurbished'), ('used', 'Used'), ('untested', 'Untested'), ('salvage', 'Salvage'), ('as_is', 'As-Is')], max_length=30, verbose_name='condition'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro')], default='USD', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='unit_type',
            field=models.CharField(choices=[('piece', 'Piece'), ('carton', 'Carton'), ('pallet', 'Pallet'), ('set', 'Set'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('lot', 'Lot'), ('truckload', 'Truckload'), ('container_20ft', '20ft Container'), ('container_40ft', '40ft Container')], default='piece', max_length=20, verbose_name='unit type'),
        ),
    ]
